/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Devishree V
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form.dialogs;

import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.form.LayeredCanvas;
import in.raster.mayam.form.display.Display;

/**
 *
 * @author BabuHussain
 * @version 0.5
 *
 */
public class ExportDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    public static boolean seriesOfImage;
    public static boolean conversionFormatDcm;
    boolean isStudy;

    /**
     * Creates new form AEManagementDialog
     */
    public ExportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public void selectedRadio() {
        if (singleImage.isSelected()) {
            seriesOfImage = false;
        } else if (allImageRadio.isSelected()) {
            seriesOfImage = true;
        } else {
            isStudy = true;
        }
    }

    public void selectedFormat() {
        if (dicomRadio.isSelected()) {
            conversionFormatDcm = true;
        } else {
            conversionFormatDcm = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formatGroup = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        singleImage = new javax.swing.JRadioButton();
        allImageRadio = new javax.swing.JRadioButton();
        formatLabel = new javax.swing.JLabel();
        dicomRadio = new javax.swing.JRadioButton();
        jpgRadio = new javax.swing.JRadioButton();
        entireStudyRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ApplicationContext.currentBundle.getString("ExportDialog.title.text")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText(ApplicationContext.currentBundle.getString("ExportDialog.exportButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(ApplicationContext.currentBundle.getString("ExportDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(singleImage);
        singleImage.setSelected(true);
        singleImage.setText(ApplicationContext.currentBundle.getString("ExportDialog.currentImageRadio.text")); // NOI18N

        buttonGroup1.add(allImageRadio);
        allImageRadio.setText(ApplicationContext.currentBundle.getString("ExportDialog.allImagesRadio.text")); // NOI18N

        formatLabel.setText(ApplicationContext.currentBundle.getString("ExportDialog.formatLabel.text")); // NOI18N

        formatGroup.add(dicomRadio);
        dicomRadio.setSelected(true);
        dicomRadio.setText(ApplicationContext.currentBundle.getString("ExportDialog.dicomRadio.text")); // NOI18N

        formatGroup.add(jpgRadio);
        jpgRadio.setText(ApplicationContext.currentBundle.getString("ExportDialog.jpgRadio.text")); // NOI18N

        buttonGroup1.add(entireStudyRadio);
        entireStudyRadio.setText(ApplicationContext.currentBundle.getString("ExportDialog.entireStudy.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(168, Short.MAX_VALUE)
                        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(allImageRadio))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(singleImage))
                            .add(layout.createSequentialGroup()
                                .add(31, 31, 31)
                                .add(formatLabel)
                                .add(55, 55, 55)
                                .add(dicomRadio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jpgRadio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(entireStudyRadio)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(formatLabel)
                    .add(dicomRadio)
                    .add(jpgRadio))
                .add(26, 26, 26)
                .add(singleImage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(allImageRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(entireStudyRadio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt-action performed event
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        selectedRadio();
        selectedFormat();
        ExportLocationChooser jpegChooser = new ExportLocationChooser(ApplicationContext.imgView, true);
        this.setVisible(false);
        Display.alignScreen(jpegChooser);
        if (isStudy) {
            jpegChooser.setSeriesOrInstanceLevel(false);
            jpegChooser.setStudyUID(((LayeredCanvas) ApplicationContext.selectedPanel.getComponent(0)).imgpanel.getStudyUID());
            jpegChooser.setFromat(conversionFormatDcm);
        } else {
            jpegChooser.setSeriesOrInstanceLevel(true);
        }
        jpegChooser.hideFormatComponents();
        jpegChooser.setVisible(true);
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     *
     * @param evt-action performed event
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    /**
     * This routine used to check the status of the dicom aetitle
     *
     * @param evt
     */
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExportDialog dialog = new ExportDialog(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allImageRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton dicomRadio;
    private javax.swing.JRadioButton entireStudyRadio;
    private javax.swing.ButtonGroup formatGroup;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JRadioButton jpgRadio;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton singleImage;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
