/* ***** BEGIN LICENSE BLOCK *****
* Version: MPL 1.1/GPL 2.0/LGPL 2.1
*
* The contents of this file are subject to the Mozilla Public License Version
* 1.1 (the "License"); you may not use this file except in compliance with
* the License. You may obtain a copy of the License at
* http://www.mozilla.org/MPL/
*
* Software distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
* for the specific language governing rights and limitations under the
* License.
*
*
* The Initial Developer of the Original Code is
* Raster Images
* Portions created by the Initial Developer are Copyright (C) 2009-2010
* the Initial Developer. All Rights Reserved.
*
* Contributor(s):
* Babu Hussain A
* Meer Asgar Hussain B
* Prakash J
* Suresh V
*
* Alternatively, the contents of this file may be used under the terms of
* either the GNU General Public License Version 2 or later (the "GPL"), or
* the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
* in which case the provisions of the GPL or the LGPL are applicable instead
* of those above. If you wish to allow use of your version of this file only
* under the terms of either the GPL or the LGPL, and not to allow others to
* use your version of this file under the terms of the MPL, indicate your
* decision by deleting the provisions above and replace them with the notice
* and other provisions required by the GPL or the LGPL. If you do not delete
* the provisions above, a recipient may use your version of this file under
* the terms of any one of the MPL, the GPL or the LGPL.
*
* ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.delegate.LocalizerDelegate;
import in.raster.mayam.form.dialog.ExportDialog;
import in.raster.mayam.util.DicomTags;
import in.raster.mayam.util.DicomTagsReader;
import in.raster.mayam.form.display.Display;
import in.raster.mayam.delegate.CineTimer;
import in.raster.mayam.model.Instance;
import in.raster.mayam.model.PresetModel;
import in.raster.mayam.model.Series;
import in.raster.mayam.model.Study;
import in.raster.mayam.model.combo.WindowingComboModel;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Timer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  BabuHussain
 * @version 0.5
 *
 */
public class ImageToolbar extends javax.swing.JPanel {

    /** Creates new form ImageToolbar */
    ApplicationContext app;
    CineTimer cineTimer;
    Timer timer;
    ImageView imgView;

    public ImageToolbar() {
        initComponents();
        app = new ApplicationContext();
        cineTimer = new CineTimer();
    }

    public ImageToolbar(ImageView imgView) {
        initComponents();
        app = new ApplicationContext();
        cineTimer = new CineTimer();
        this.imgView = imgView;
        designPopup();
        // presetButton.setVisible(false);
        jComboBox1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jToolBar3 = new javax.swing.JToolBar();
        layoutButton = new javax.swing.JButton();
        windowing = new javax.swing.JButton();
        presetButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        probeButton = new javax.swing.JButton();
        verticalFlip = new javax.swing.JButton();
        horizontalFlip = new javax.swing.JButton();
        leftRotate = new javax.swing.JButton();
        rightRotate = new javax.swing.JButton();
        zoomin = new javax.swing.JButton();
        zoomoutButton = new javax.swing.JButton();
        panButton = new javax.swing.JButton();
        invert = new javax.swing.JButton();
        rulerButton = new javax.swing.JButton();
        rectangleButton = new javax.swing.JButton();
        ellipseButton = new javax.swing.JButton();
        clearAllMeasurement = new javax.swing.JButton();
        deleteMeasurement = new javax.swing.JButton();
        moveMeasurement = new javax.swing.JButton();
        textOverlay = new javax.swing.JButton();
        annotationVisibility = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stackButton = new javax.swing.JButton();
        scoutButton = new javax.swing.JButton();
        loopCheckbox = new javax.swing.JCheckBox();
        loopSlider = new javax.swing.JSlider();

        setBackground(new java.awt.Color(102, 102, 102));

        jToolBar3.setRollover(true);

        layoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/layout.png"))); // NOI18N
        layoutButton.setToolTipText("Layout");
        layoutButton.setBorderPainted(false);
        layoutButton.setComponentPopupMenu(jPopupMenu1);
        layoutButton.setFocusable(false);
        layoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        layoutButton.setPreferredSize(new java.awt.Dimension(45, 45));
        layoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        layoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layoutButtonMouseClicked(evt);
            }
        });
        jToolBar3.add(layoutButton);

        windowing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/windowing.png"))); // NOI18N
        windowing.setToolTipText("Windowing");
        windowing.setBorderPainted(false);
        windowing.setFocusable(false);
        windowing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windowing.setPreferredSize(new java.awt.Dimension(45, 45));
        windowing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        windowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowingActionPerformed(evt);
            }
        });
        jToolBar3.add(windowing);

        presetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/drop_down.png"))); // NOI18N
        presetButton.setToolTipText("Preset");
        presetButton.setBorderPainted(false);
        presetButton.setComponentPopupMenu(jPopupMenu2);
        presetButton.setFocusable(false);
        presetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        presetButton.setMaximumSize(new java.awt.Dimension(12, 24));
        presetButton.setMinimumSize(new java.awt.Dimension(12, 24));
        presetButton.setPreferredSize(new java.awt.Dimension(45, 45));
        presetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        presetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presetButtonMouseClicked(evt);
            }
        });
        jToolBar3.add(presetButton);

        jComboBox1.setModel(new WindowingComboModel(ApplicationContext.databaseRef.getPresets()));
        jComboBox1.setMinimumSize(new java.awt.Dimension(20, 3));
        jComboBox1.setPreferredSize(new java.awt.Dimension(47, 3));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar3.add(jComboBox1);

        probeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/probe.png"))); // NOI18N
        probeButton.setToolTipText("Probe");
        probeButton.setBorderPainted(false);
        probeButton.setFocusable(false);
        probeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        probeButton.setPreferredSize(new java.awt.Dimension(45, 45));
        probeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        probeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probeButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(probeButton);

        verticalFlip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/flip_vertical.png"))); // NOI18N
        verticalFlip.setToolTipText("Vertical Flip");
        verticalFlip.setBorderPainted(false);
        verticalFlip.setFocusable(false);
        verticalFlip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        verticalFlip.setPreferredSize(new java.awt.Dimension(45, 45));
        verticalFlip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        verticalFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalFlipActionPerformed(evt);
            }
        });
        jToolBar3.add(verticalFlip);

        horizontalFlip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/flip_horizontal.png"))); // NOI18N
        horizontalFlip.setToolTipText("Horizontal Flip");
        horizontalFlip.setBorderPainted(false);
        horizontalFlip.setFocusable(false);
        horizontalFlip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        horizontalFlip.setPreferredSize(new java.awt.Dimension(45, 45));
        horizontalFlip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        horizontalFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalFlipActionPerformed(evt);
            }
        });
        jToolBar3.add(horizontalFlip);

        leftRotate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/rotate_left.png"))); // NOI18N
        leftRotate.setToolTipText("Rotate Left");
        leftRotate.setBorderPainted(false);
        leftRotate.setFocusable(false);
        leftRotate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftRotate.setPreferredSize(new java.awt.Dimension(45, 45));
        leftRotate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRotateActionPerformed(evt);
            }
        });
        jToolBar3.add(leftRotate);

        rightRotate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/rotate_right.png"))); // NOI18N
        rightRotate.setToolTipText("Rotate Right");
        rightRotate.setBorderPainted(false);
        rightRotate.setFocusable(false);
        rightRotate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightRotate.setPreferredSize(new java.awt.Dimension(45, 45));
        rightRotate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightRotateActionPerformed(evt);
            }
        });
        jToolBar3.add(rightRotate);

        zoomin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/zoomin.png"))); // NOI18N
        zoomin.setToolTipText("Zoom In");
        zoomin.setBorderPainted(false);
        zoomin.setFocusable(false);
        zoomin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomin.setPreferredSize(new java.awt.Dimension(45, 45));
        zoomin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoominActionPerformed(evt);
            }
        });
        jToolBar3.add(zoomin);

        zoomoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/zoomout.png"))); // NOI18N
        zoomoutButton.setToolTipText("Zoom Out");
        zoomoutButton.setBorderPainted(false);
        zoomoutButton.setFocusable(false);
        zoomoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomoutButton.setPreferredSize(new java.awt.Dimension(45, 45));
        zoomoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomoutButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(zoomoutButton);

        panButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/pan.png"))); // NOI18N
        panButton.setToolTipText("Pan");
        panButton.setBorderPainted(false);
        panButton.setFocusable(false);
        panButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panButton.setPreferredSize(new java.awt.Dimension(45, 45));
        panButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(panButton);

        invert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/invert.png"))); // NOI18N
        invert.setToolTipText("Invert");
        invert.setBorderPainted(false);
        invert.setFocusable(false);
        invert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        invert.setPreferredSize(new java.awt.Dimension(45, 45));
        invert.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        invert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertActionPerformed(evt);
            }
        });
        jToolBar3.add(invert);

        rulerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/ruler.png"))); // NOI18N
        rulerButton.setToolTipText("Ruler");
        rulerButton.setBorderPainted(false);
        rulerButton.setFocusable(false);
        rulerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rulerButton.setPreferredSize(new java.awt.Dimension(45, 45));
        rulerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulerButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(rulerButton);

        rectangleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/rectangle.png"))); // NOI18N
        rectangleButton.setToolTipText("Rectangle ROI");
        rectangleButton.setBorderPainted(false);
        rectangleButton.setFocusable(false);
        rectangleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangleButton.setPreferredSize(new java.awt.Dimension(45, 45));
        rectangleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(rectangleButton);

        ellipseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/ellipse.png"))); // NOI18N
        ellipseButton.setToolTipText("Elliptical ROI");
        ellipseButton.setBorderPainted(false);
        ellipseButton.setFocusable(false);
        ellipseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ellipseButton.setPreferredSize(new java.awt.Dimension(45, 45));
        ellipseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ellipseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ellipseButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(ellipseButton);

        clearAllMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/clear_all_annotation.png"))); // NOI18N
        clearAllMeasurement.setToolTipText("Clear All Measurement");
        clearAllMeasurement.setBorderPainted(false);
        clearAllMeasurement.setPreferredSize(new java.awt.Dimension(45, 45));
        clearAllMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllMeasurementActionPerformed(evt);
            }
        });
        jToolBar3.add(clearAllMeasurement);

        deleteMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/delete_annotation.png"))); // NOI18N
        deleteMeasurement.setToolTipText("Delete Measurement");
        deleteMeasurement.setBorderPainted(false);
        deleteMeasurement.setFocusable(false);
        deleteMeasurement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteMeasurement.setPreferredSize(new java.awt.Dimension(45, 45));
        deleteMeasurement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMeasurementActionPerformed(evt);
            }
        });
        jToolBar3.add(deleteMeasurement);

        moveMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/annotation_selection.png"))); // NOI18N
        moveMeasurement.setToolTipText("Measurement Selection");
        moveMeasurement.setBorderPainted(false);
        moveMeasurement.setDoubleBuffered(true);
        moveMeasurement.setFocusable(false);
        moveMeasurement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moveMeasurement.setPreferredSize(new java.awt.Dimension(45, 45));
        moveMeasurement.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        moveMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveMeasurementActionPerformed(evt);
            }
        });
        jToolBar3.add(moveMeasurement);

        textOverlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/textoverlay.png"))); // NOI18N
        textOverlay.setToolTipText("Text Overlay");
        textOverlay.setBorderPainted(false);
        textOverlay.setFocusable(false);
        textOverlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textOverlay.setPreferredSize(new java.awt.Dimension(45, 45));
        textOverlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        textOverlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOverlayActionPerformed(evt);
            }
        });
        jToolBar3.add(textOverlay);

        annotationVisibility.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/annotation_overlay.png"))); // NOI18N
        annotationVisibility.setToolTipText("Annotation Overlay");
        annotationVisibility.setBorderPainted(false);
        annotationVisibility.setFocusable(false);
        annotationVisibility.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        annotationVisibility.setPreferredSize(new java.awt.Dimension(45, 45));
        annotationVisibility.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        annotationVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annotationVisibilityActionPerformed(evt);
            }
        });
        jToolBar3.add(annotationVisibility);

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/reset.png"))); // NOI18N
        reset.setToolTipText("Reset");
        reset.setBorderPainted(false);
        reset.setFocusable(false);
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.setPreferredSize(new java.awt.Dimension(45, 45));
        reset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jToolBar3.add(reset);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/export_series.png"))); // NOI18N
        jButton1.setToolTipText("Export");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/metadata_viewerpage.png"))); // NOI18N
        jButton2.setToolTipText("Meta Data");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton2);

        stackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/stack.png"))); // NOI18N
        stackButton.setToolTipText("Stack");
        stackButton.setBorderPainted(false);
        stackButton.setFocusable(false);
        stackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stackButton.setPreferredSize(new java.awt.Dimension(45, 45));
        stackButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(stackButton);

        scoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/raster/mayam/form/images/scout.png"))); // NOI18N
        scoutButton.setToolTipText("ScoutLine");
        scoutButton.setBorderPainted(false);
        scoutButton.setFocusable(false);
        scoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scoutButton.setPreferredSize(new java.awt.Dimension(45, 45));
        scoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoutButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(scoutButton);

        loopCheckbox.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        loopCheckbox.setText("Loop");
        loopCheckbox.setFocusable(false);
        loopCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loopCheckbox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loopCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopCheckboxActionPerformed(evt);
            }
        });
        loopCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loopCheckboxStateChanged(evt);
            }
        });
        jToolBar3.add(loopCheckbox);

        loopSlider.setMaximum(9);
        loopSlider.setPaintTicks(true);
        loopSlider.setValue(6);
        loopSlider.setDoubleBuffered(true);
        loopSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                loopSliderStateChanged(evt);
            }
        });
        jToolBar3.add(loopSlider);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rightRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightRotateActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.rotateRight();
            ApplicationContext.annotationPanel.doRotateRight();
        } else {
            JOptionPane.showMessageDialog(this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_rightRotateActionPerformed

    private void leftRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftRotateActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.rotateLeft();
            ApplicationContext.annotationPanel.doRotateLeft();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_leftRotateActionPerformed

    private void invertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.negative();

        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_invertActionPerformed

    private void horizontalFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalFlipActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.flipHorizontal();
            ApplicationContext.annotationPanel.doFlipHorizontal();
            ApplicationContext.imgPanel.repaint();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_horizontalFlipActionPerformed

    private void verticalFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalFlipActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.flipVertical();
            ApplicationContext.annotationPanel.doFlipVertical();
            ApplicationContext.imgPanel.repaint();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_verticalFlipActionPerformed

    private void windowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowingActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.setAddLine(false);
            ApplicationContext.annotationPanel.setAddEllipse(false);
            ApplicationContext.annotationPanel.setAddRect(false);
            ApplicationContext.annotationPanel.stopPanning();
            ApplicationContext.imgPanel.doWindowing();
        }
}//GEN-LAST:event_windowingActionPerformed

    private void zoominActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoominActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            resetTools();
            ApplicationContext.imgPanel.doZoomIn();
            ApplicationContext.annotationPanel.doZoomIn();
            ApplicationContext.imgPanel.repaint();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_zoominActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.reset();
            ApplicationContext.annotationPanel.reset();
            ApplicationContext.annotationPanel.clearAllMeasurement();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_resetActionPerformed

    private void textOverlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOverlayActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.layeredCanvas.textOverlay.toggleTextOverlay();

        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_textOverlayActionPerformed

    private void probeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probeButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.setAddLine(false);
            ApplicationContext.annotationPanel.setAddEllipse(false);
            ApplicationContext.annotationPanel.setAddRect(false);
            ApplicationContext.annotationPanel.stopPanning();
            ApplicationContext.imgPanel.probe();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_probeButtonActionPerformed

    private void panButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.setAddLine(false);
            ApplicationContext.annotationPanel.setAddEllipse(false);
            ApplicationContext.annotationPanel.setAddRect(false);
            ApplicationContext.imgPanel.doPan();
            ApplicationContext.annotationPanel.doPan();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_panButtonActionPerformed

    private void zoomoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomoutButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            resetTools();
            ApplicationContext.imgPanel.doZoomOut();
            ApplicationContext.annotationPanel.doZoomOut();
            ApplicationContext.imgPanel.repaint();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_zoomoutButtonActionPerformed
    private void resetTools() {
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.setMouseLocX1(-1);
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }

    }
    private void rulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulerButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.stopPanning();
            ApplicationContext.imgPanel.setToolsToNull();
            ApplicationContext.annotationPanel.setMouseLocX1(-1);
            if (!ApplicationContext.annotationPanel.isAddLine()) {
                ApplicationContext.annotationPanel.setAddLine(true);
                ApplicationContext.annotationPanel.setAddEllipse(false);
                ApplicationContext.annotationPanel.setAddRect(false);
            } else {
                ApplicationContext.annotationPanel.setAddLine(false);
            }
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }

}//GEN-LAST:event_rulerButtonActionPerformed

    private void stackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.stopPanning();
            storeAnnotationHook();
            ApplicationContext.annotationPanel.setAddLine(false);
            ApplicationContext.annotationPanel.setAddEllipse(false);
            ApplicationContext.annotationPanel.setAddRect(false);
            ApplicationContext.imgPanel.doStack();
            ApplicationContext.imgPanel.repaint();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_stackButtonActionPerformed

    private void loopSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loopSliderStateChanged

        try {
            if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
                if (loopCheckbox.isSelected()) {
                    if (timer != null) {
                        timer.cancel();
                        timer = new Timer();
                        timer.scheduleAtFixedRate(new CineTimer(), 0, (11 - loopSlider.getValue()) * 100);//

                    } else {
                        timer = new Timer();
                        timer.scheduleAtFixedRate(new CineTimer(), 0, (11 - loopSlider.getValue()) * 100);//
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }



}//GEN-LAST:event_loopSliderStateChanged

    private void loopCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_loopCheckboxStateChanged
}//GEN-LAST:event_loopCheckboxStateChanged

    private void loopCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopCheckboxActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            if (loopCheckbox.isSelected()) {
                storeAnnotationHook();
                try {
                    timer = new Timer();
                    timer.scheduleAtFixedRate(new CineTimer(), 0, (11 - loopSlider.getValue()) * 100);//
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                if (timer != null) {
                    timer.cancel();
                }
            }
        } else {
            loopCheckbox.setSelected(false);
        }
}//GEN-LAST:event_loopCheckboxActionPerformed

    public void resetCineTimer() {
        if (timer != null) {
            timer.cancel();
        }
    }
    private void rectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.stopPanning();
            ApplicationContext.imgPanel.setToolsToNull();
            ApplicationContext.annotationPanel.setMouseLocX1(-1);
            if (!ApplicationContext.annotationPanel.isAddRect()) {
                ApplicationContext.annotationPanel.setAddLine(false);
                ApplicationContext.annotationPanel.setAddEllipse(false);
                ApplicationContext.annotationPanel.setAddRect(true);
            } else {
                ApplicationContext.annotationPanel.setAddRect(false);
            }
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }

}//GEN-LAST:event_rectangleButtonActionPerformed

    private void ellipseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ellipseButtonActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.annotationPanel.stopPanning();
            ApplicationContext.imgPanel.setToolsToNull();
            ApplicationContext.annotationPanel.setMouseLocX1(-1);
            if (!ApplicationContext.annotationPanel.isAddEllipse()) {
                ApplicationContext.annotationPanel.setAddLine(false);
                ApplicationContext.annotationPanel.setAddEllipse(true);
                ApplicationContext.annotationPanel.setAddRect(false);
            } else {
                ApplicationContext.annotationPanel.setAddEllipse(false);
            }
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_ellipseButtonActionPerformed

    private void clearAllMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllMeasurementActionPerformed
        if (ApplicationContext.annotationPanel != null) {
            ApplicationContext.annotationPanel.clearAllMeasurement();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_clearAllMeasurementActionPerformed

    private void annotationVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annotationVisibilityActionPerformed
        if (ApplicationContext.annotationPanel != null) {
            ApplicationContext.annotationPanel.toggleAnnotation();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_annotationVisibilityActionPerformed

    private void deleteMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMeasurementActionPerformed
        if (ApplicationContext.annotationPanel != null) {
            ApplicationContext.annotationPanel.doDeleteMeasurement();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_deleteMeasurementActionPerformed
    // ApplicationContext.annotationPanel.doResizeMeasurement();
    private void moveMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveMeasurementActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ApplicationContext.imgPanel.tool = "";
            ApplicationContext.annotationPanel.doMoveMeasurement();
        } else {
            JOptionPane.showMessageDialog(ImageToolbar.this, "Tile selected is not valid for this process");
        }
}//GEN-LAST:event_moveMeasurementActionPerformed

    private void layoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layoutButtonMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        long z = evt.getWhen();
        int mo = evt.getModifiers();
        int cc = evt.getClickCount();

        layoutButton.dispatchEvent(new java.awt.event.MouseEvent(this.layoutButton, MouseEvent.MOUSE_CLICKED, z, mo, x, y, cc, true));
        storeAnnotationHook();
}//GEN-LAST:event_layoutButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ExportDialog jpegConvertor = new ExportDialog(ApplicationContext.imgView, true);
            Display.alignScreen(jpegConvertor);
            jpegConvertor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void presetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presetButtonMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        long z = evt.getWhen();
        int mo = evt.getModifiers();
        int cc = evt.getClickCount();
        designPresetContext();
        presetButton.dispatchEvent(new java.awt.event.MouseEvent(this.presetButton, MouseEvent.MOUSE_CLICKED, z, mo, x, y, cc, true));

    }//GEN-LAST:event_presetButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ArrayList<DicomTags> dcmTags = DicomTagsReader.getTags(new File(ApplicationContext.imgPanel.getDicomFileUrl()));
            DicomTagsViewer dicomTagsViewer = new DicomTagsViewer(dcmTags);
            Display.alignScreen(dicomTagsViewer);
            dicomTagsViewer.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Tile selected is not valid for this process");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        PresetModel presetModel = ApplicationContext.databaseRef.getPreset((String) ((JComboBox) evt.getSource()).getSelectedItem());
        if (presetModel.getPresetName() != null) {
            ApplicationContext.imgPanel.windowChanged(Integer.parseInt(presetModel.getWindowLevel()), Integer.parseInt(presetModel.getWindowWidth()));
        } else {
            ApplicationContext.imgPanel.resetWindowing();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void scoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoutButtonActionPerformed
        if (!ApplicationContext.imgPanel.isDisplayScout()) {
            ApplicationContext.imgPanel.setDisplayScout(true);
            LocalizerDelegate localizer = new LocalizerDelegate();
            localizer.drawScoutLineWithBorder();
        } else {
            ApplicationContext.imgPanel.setDisplayScout(false);
            LocalizerDelegate.hideScoutLine();
        }
    }//GEN-LAST:event_scoutButtonActionPerformed
    private void designPresetContext() {
        if (ApplicationContext.annotationPanel != null && ApplicationContext.imgPanel != null) {
            ArrayList presetList = ApplicationContext.databaseRef.getPresetValueForModality(ApplicationContext.imgPanel.getModality());
            jPopupMenu2.removeAll();
            JMenuItem menu = new JMenuItem("PRESETS");
            jPopupMenu2.add(menu);
            jPopupMenu2.addSeparator();
            for (int i = 0; i < presetList.size(); i++) {
                final PresetModel presetModel = (PresetModel) presetList.get(i);
                if (!presetModel.getPresetName().equalsIgnoreCase("PRESETNAME")) {
                    JMenuItem menu1 = new JMenuItem(presetModel.getPresetName());
                    jPopupMenu2.add(menu1);
                    menu1.addActionListener(new ActionListener() {

                        public void actionPerformed(ActionEvent e) {
                            ApplicationContext.imgPanel.windowChanged(Integer.parseInt(presetModel.getWindowLevel()), Integer.parseInt(presetModel.getWindowWidth()));

                        }
                    });
                }
            }
            this.setComponentPopupMenu(jPopupMenu1);
        } else {
            JOptionPane.showMessageDialog(this, "Tile selected is not valid for this process");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annotationVisibility;
    private javax.swing.JButton clearAllMeasurement;
    private javax.swing.JButton deleteMeasurement;
    private javax.swing.JButton ellipseButton;
    private javax.swing.JButton horizontalFlip;
    private javax.swing.JButton invert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton layoutButton;
    private javax.swing.JButton leftRotate;
    private javax.swing.JCheckBox loopCheckbox;
    private javax.swing.JSlider loopSlider;
    private javax.swing.JButton moveMeasurement;
    private javax.swing.JButton panButton;
    private javax.swing.JButton presetButton;
    private javax.swing.JButton probeButton;
    private javax.swing.JButton rectangleButton;
    private javax.swing.JButton reset;
    private javax.swing.JButton rightRotate;
    private javax.swing.JButton rulerButton;
    private javax.swing.JButton scoutButton;
    private javax.swing.JButton stackButton;
    private javax.swing.JButton textOverlay;
    private javax.swing.JButton verticalFlip;
    private javax.swing.JButton windowing;
    private javax.swing.JButton zoomin;
    private javax.swing.JButton zoomoutButton;
    // End of variables declaration//GEN-END:variables

    public void designPopup() {
        JPanel jp = new JPanel(new GridLayout(3, 3));
        JButton jb1 = new JButton("1x1");
        JButton jb2 = new JButton("1x2");
        JButton jb3 = new JButton("1x3");
        JButton jb4 = new JButton("2x1");
        JButton jb5 = new JButton("2x2");
        JButton jb6 = new JButton("2x3");
        JButton jb7 = new JButton("3x1");
        JButton jb8 = new JButton("3x2");
        JButton jb9 = new JButton("3x3");
        jp.add(jb1);
        jp.add(jb2);
        jp.add(jb3);
        jp.add(jb4);
        jp.add(jb5);
        jp.add(jb6);
        jp.add(jb7);
        jp.add(jb8);
        jp.add(jb9);
        jp.setBounds(0, 0, 200, 400);
        jPopupMenu1.add(jp);

        jb1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jb2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jb3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jb4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jb5.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        jb6.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        jb7.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        jb8.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        jb9.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

    }

    public void jb1ActionPerformed(ActionEvent e) {
        changeLayout(1, 1);

    }

    public void storeAnnotationHook() {
        for (int i = 0; i < ApplicationContext.imgView.jTabbedPane1.getComponentCount(); i++) {
            for (int j = 0; j < ((JPanel) ApplicationContext.imgView.jTabbedPane1.getComponent(i)).getComponentCount(); j++) {
                try {
                    ((LayeredCanvas) ((JPanel) ApplicationContext.imgView.jTabbedPane1.getComponent(i)).getComponent(j)).imgpanel.storeAnnotation();
                } catch (Exception e) {
                    //Class cast exception because it is not a layered canvas
                }
            }
        }
    }

    private void removeAllPanelsFromSelectedTab() {
        for (int i = ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponentCount() - 1; i >= 0; i--) {
            ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).remove(i);
        }
    }

    public void changeLayout(int row, int col) {
        String siuid;
        if (ApplicationContext.imgPanel != null) {
            siuid = ApplicationContext.imgPanel.getStudyUID();
        } else {
            siuid = ApplicationContext.layeredCanvas.getStudyUID();
        }

        GridLayout g = new GridLayout(row, col);
        ArrayList<Instance> instanceArray = getInstanceArray();
        ArrayList tempRef = ApplicationContext.databaseRef.getUrlBasedOnStudyIUID(siuid);
        for (int i = ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponentCount() - 1; i >= 0; i--) {
            ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).remove(i);

        }
        ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).setLayout(g);
        for (int i = 0; i < (row * col); i++) {
            if (i < tempRef.size()) {
                File file = (File) tempRef.get(i);
                LayeredCanvas canvas = new LayeredCanvas(file.getAbsolutePath());
                ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).add(canvas, i);
                for (int x = 0; x < instanceArray.size(); x++) {
                    if (file.getAbsolutePath().equalsIgnoreCase(instanceArray.get(x).getFilepath())) {
                        ((LayeredCanvas) ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponent(i)).annotationPanel.setAnnotation(instanceArray.get(x).getAnnotation());
                    }
                }
            } else {
                LayeredCanvas j = new LayeredCanvas();
                j.setStudyUID(siuid);
                ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).add(j, i);
            }
        }
        ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).revalidate();
        ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).repaint();
        ApplicationContext.imgPanel = ((LayeredCanvas) ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponent(0)).imgpanel;
        ApplicationContext.annotationPanel = ((LayeredCanvas) ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponent(0)).annotationPanel;
        ApplicationContext.layeredCanvas = ((LayeredCanvas) ((JPanel) ApplicationContext.imgView.jTabbedPane1.getSelectedComponent()).getComponent(0));
        hideLayoutSelectionPopup();
        ((Canvas) ApplicationContext.imgPanel.getCanvas()).setSelection();
        //storeAnnotationHook();
    }

    private void hideLayoutSelectionPopup() {
        jPopupMenu1.setVisible(false);
    }

    public ArrayList getInstanceArray() {
        ArrayList<Instance> instanceArray = new ArrayList<Instance>();
        String studyUID = "";
        if (ApplicationContext.imgPanel != null) {
            studyUID = ApplicationContext.imgPanel.getStudyUID();
        } else {
            studyUID = ApplicationContext.layeredCanvas.getStudyUID();
        }

        Iterator<Study> studyItr = MainScreen.studyList.iterator();
        while (studyItr.hasNext()) {
            Study study = studyItr.next();
            if (study.getStudyInstanceUID().equalsIgnoreCase(studyUID)) {
                ArrayList<Series> seriesList = (ArrayList<Series>) study.getSeriesList();
                for (int i = 0; i < seriesList.size(); i++) {
                    Series series = seriesList.get(i);
                    Instance instance = series.getImageList().get(0);
                    instanceArray.add(instance);
                    //   this.getCanvas().getLayeredCanvas().annotationPanel.setAnnotation(instance.getAnnotation());
                }
            }
        }
        return instanceArray;
    }

    public void jb2ActionPerformed(ActionEvent e) {
        changeLayout(1, 2);
    }

    public void jb3ActionPerformed(ActionEvent e) {
        changeLayout(1, 3);
    }

    public void jb4ActionPerformed(ActionEvent e) {
        changeLayout(2, 1);
    }

    public void jb5ActionPerformed(ActionEvent e) {
        changeLayout(2, 2);
    }

    public void jb6ActionPerformed(ActionEvent e) {
        changeLayout(2, 3);
    }

    public void jb7ActionPerformed(ActionEvent e) {
        changeLayout(3, 1);
    }

    public void jb8ActionPerformed(ActionEvent e) {
        changeLayout(3, 2);
    }

    public void jb9ActionPerformed(ActionEvent e) {
        changeLayout(3, 3);
    }
}
