/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Devishree V
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.context.ApplicationContext;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author Devishree
 * @version 2.0
 */
public class ImagePreviewPanel extends javax.swing.JPanel {

    public JPanel parent = new JPanel();
    String[] labelInfo;
    String studyInstanceUid = "";

    /**
     * Creates new form ImagePreviewPanel
     */
    public ImagePreviewPanel() {
        initComponents();
        container.setLayout(new GridLayout(1, 1));
        parent.setLayout(null);
        patientDetailsLabel.setFont(ApplicationContext.textFont);
        patientDetailsLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDetailsLabel = new javax.swing.JLabel();
        seriesScrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        patientDetailsLabel.setText("jLabel1");
        patientDetailsLabel.setMaximumSize(new java.awt.Dimension(44, 12));
        patientDetailsLabel.setMinimumSize(new java.awt.Dimension(44, 12));
        patientDetailsLabel.setPreferredSize(new java.awt.Dimension(44, 12));

        seriesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        seriesScrollPane.getVerticalScrollBar().setUnitIncrement(20);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        seriesScrollPane.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seriesScrollPane)
                    .addComponent(patientDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(patientDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seriesScrollPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel patientDetailsLabel;
    private javax.swing.JScrollPane seriesScrollPane;
    // End of variables declaration//GEN-END:variables

    public void paint(int size) {
        parent.setBounds(0, 0, 240, size);
        container.add(parent);
        container.setPreferredSize(new Dimension(230, size));
        container.revalidate();
        container.repaint();
        seriesScrollPane.repaint();
        seriesScrollPane.validate();
    }

    public void addViewerPanel(int pos, int size, ViewerPreviewPanel viewerPreviewPanel, int totalSize) {
        container.remove(parent);
        container.revalidate();
        container.repaint();
        viewerPreviewPanel.setBounds(0, pos, 240, size);
        parent.add(viewerPreviewPanel);
        parent.setBounds(0, 0, 240, totalSize);
        parent.revalidate();
        parent.repaint();
        container.add(parent);
        container.setPreferredSize(new Dimension(230, totalSize));
        container.revalidate();
        container.repaint();
    }

    public void addPreviewPanel(int pos, int size, PreviewPanel previewPanel, int totalSize) {
        previewPanel.setBounds(0, pos, 230, size);
        parent.add(previewPanel);
        parent.setBounds(0, 0, 230, totalSize);
        parent.revalidate();
        parent.repaint();
        container.add(parent);
        container.setPreferredSize(new Dimension(230, totalSize));
        container.revalidate();
        container.repaint();
    }

    public void setPatientInfo(String[] labelsInfo) {
        this.labelInfo = labelsInfo;
        patientDetailsLabel.setText("<html><body>" + labelsInfo[0] + "<br>" + labelsInfo[1] + "<br>" + labelsInfo[2] + "<br>" + labelsInfo[3] + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + labelsInfo[4] + "</body></html");
    }

    public void clearPatientInfo() {
        patientDetailsLabel.setText("");
    }

    public void resetPreviewPanel() {
        container.remove(parent);
        parent.removeAll();
        parent.setBounds(0, 0, 230, 200);
        container.setPreferredSize(new Dimension(230, 200));
        parent.revalidate();
        parent.repaint();
        container.add(parent);
        container.revalidate();
        container.repaint();
        seriesScrollPane.repaint();
        seriesScrollPane.validate();
    }

    public void resetImagePreviewPanel() {
        clearPatientInfo();
        container.remove(parent);
        parent.removeAll();
        parent.setBounds(0, 0, 230, 200);
        container.setPreferredSize(new Dimension(230, 200));
        parent.revalidate();
        parent.repaint();
        container.add(parent);
        container.revalidate();
        container.repaint();
        seriesScrollPane.repaint();
        seriesScrollPane.validate();
    }

    public String getPatientInfo() {
        return patientDetailsLabel.getText();
    }

    public void setPatientInfo(String patientInfo) {
        patientDetailsLabel.setText(patientInfo);
    }

    public String[] getLabelInfo() {
        return labelInfo;
    }

    public String getPatientId() {
        if (labelInfo != null) {
            return labelInfo[1];
        } else {
            return "";
        }
    }

    public String getPreviousStudyUid() {
        return studyInstanceUid;
    }

    public void setPreviousStudyUid(String studyUid) {
        studyInstanceUid = studyUid;
    }
}
