/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Devishree V
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.models.SeriesAnnotations;
import in.raster.mayam.models.StudyAnnotation;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author Devishree
 * @version 2.0
 */
public class ImageView extends javax.swing.JFrame {

    public HashMap<String, StudyAnnotation> studyAnnotaions = null;

    /**
     * Creates new form ImageView
     */
    public ImageView() {
        initComponents();
        studyAnnotaions = new HashMap<String, StudyAnnotation>(0, 1);
        imageToolbar.addKeyEventToViewer();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        applyLocale();
        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                try {
                    if (((JSplitPane) ApplicationContext.tabbedPane.getSelectedComponent()).getRightComponent() instanceof VideoPanel) {
                        imageToolbar.disableImageTools();
                        ApplicationContext.layeredCanvas = null;
                        ApplicationContext.selectedPanel = null;
                    } else {
                        imageToolbar.enableImageTools();
                        JPanel comp = ((JPanel) ((JSplitPane) ApplicationContext.tabbedPane.getSelectedComponent()).getRightComponent());
                        for (int i = 0; i < comp.getComponentCount(); i++) {
                            JPanel seriesLevelPanel = (JPanel) comp.getComponent(i);
                            for (int j = 0; j < seriesLevelPanel.getComponentCount(); j++) {
                                if (((LayeredCanvas) seriesLevelPanel.getComponent(j)).canvas.focusGained) {
                                    ApplicationContext.layeredCanvas = ((LayeredCanvas) seriesLevelPanel.getComponent(j));
                                    break;
                                }
                            }
                        }
                    }
                    imageToolbar.setWindowing();
                } catch (NullPointerException npe) {
                    //Null pointer exception occurs when the first time the tab was opened
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        imageToolbar = imageToolbar = new in.raster.mayam.form.ImageToolbar(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ApplicationContext.currentBundle.getString("ImageView.title.text")); // NOI18N
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/in/raster/mayam/form/images/fav_mayam.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowCloseHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(imageToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowCloseHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowCloseHandler
        onWindowClose();
    }//GEN-LAST:event_windowCloseHandler
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private in.raster.mayam.form.ImageToolbar imageToolbar;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public ImageToolbar getImageToolbar() {
        return this.imageToolbar;
    }

    public void applyLocale() {
        setTitle(ApplicationContext.currentBundle.getString("ImageView.title.text"));
        imageToolbar.applyLocale();
        try {
            for (int i = 0; i < ApplicationContext.tabbedPane.getTabCount(); i++) {
                JPanel panel = ((JPanel) ((JSplitPane) ApplicationContext.tabbedPane.getComponentAt(i)).getRightComponent());
                for (int j = 0; j < panel.getComponentCount(); j++) {
                    if (!(panel instanceof VideoPanel)) {
                        JPanel seriesLevelPanel = (JPanel) panel.getComponent(j);
                        for (int k = 0; k < seriesLevelPanel.getComponentCount(); k++) {
                            if (seriesLevelPanel.getComponent(k) instanceof LayeredCanvas) {
                                LayeredCanvas tempCanvas = (LayeredCanvas) seriesLevelPanel.getComponent(k);
                                if (tempCanvas.textOverlay != null) {
                                    tempCanvas.textOverlay.repaint();
                                    tempCanvas.imgpanel.displayZoomLevel();
                                }
                            }
                        }
                    } else {
                        ((VideoPanel) panel).updateLocale();
                    }
                }
            }
        } catch (NullPointerException npe) {
            //ignore Null pointer occurs when jtabbed pane has no components
        }
    }

    private void saveAnnotations() {
        for (int i = 0; i < ApplicationContext.tabbedPane.getTabCount(); i++) {
            JPanel panel = ((JPanel) ((JSplitPane) ApplicationContext.tabbedPane.getComponentAt(i)).getRightComponent());
            if (!(panel instanceof VideoPanel)) {
                for (int j = 0; j < panel.getComponentCount(); j++) {
                    JPanel seriesLevelPanel = (JPanel) panel.getComponent(j);
                    for (int k = 0; k < seriesLevelPanel.getComponentCount(); k++) {
                        if (seriesLevelPanel.getComponent(k) instanceof LayeredCanvas) {
                            LayeredCanvas tempCanvas = (LayeredCanvas) seriesLevelPanel.getComponent(k);
                            try {
                                tempCanvas.imgpanel.storeAnnotation();
                                tempCanvas.imgpanel.storeMultiframeAnnotation();
                            } catch (NullPointerException ex) {
                                //Null pointer exception occurs when there is no image panel
                            }
                        }
                    }
                }
                try {
                    writeToFile(panel.getName(), ((LayeredCanvas) ((JPanel) panel.getComponent(0)).getComponent(0)).imgpanel.getSeriesLocation());
                } catch (ArrayIndexOutOfBoundsException ex) {
                    //ignore exception occurs if the study is video and it was played using the default media player.
                }
            } else {
                ((VideoPanel) panel).stopTimer();
                EmbeddedMediaPlayerComponent mediaPlayerComp = (EmbeddedMediaPlayerComponent) ((JPanel) panel.getComponent(0)).getComponent(0);
                mediaPlayerComp.getMediaPlayer().stop();
                mediaPlayerComp.getMediaPlayer().release();
                mediaPlayerComp.getMediaPlayerFactory().release();
                mediaPlayerComp.release();
                panel.removeAll();
            }
        }
    }

    public void writeToFile(String studyUid, String fileLoc) {
        if (fileLoc.contains(ApplicationContext.getAppDirectory())) {
            FileOutputStream fos = null;
            ObjectOutputStream oos = null;
            try {
                String storeLoc = fileLoc.substring(0, fileLoc.lastIndexOf(File.separator)) + File.separator + "info.ser";
                fos = new FileOutputStream(storeLoc);
                oos = new ObjectOutputStream(fos);
                oos.writeObject(getStudyAnnotaion(studyUid));
            } catch (FileNotFoundException ex) {
                //ignore
            } catch (IOException ex) {
                //ignore
            } finally {
                try {
                    if (fos != null && oos != null) {
                        fos.close();
                        oos.close();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(ImageView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void onWindowClose() {
        if (ApplicationContext.tabbedPane != null) {
            saveAnnotations();
            studyAnnotaions = null;
            ImagePanel.setDisplayScout(false);
            imageToolbar.resetCineTimer();
            imageToolbar = null;
            ApplicationContext.imgView = null;
            ApplicationContext.tabbedPane = null;
            if (ApplicationContext.isJnlp) {
                System.exit(0);
            }
        }
    }

    public void readAnnotaionDetails(String studyInstanceUid, File annotaionInfoLoc) {
        try {
            FileInputStream fis = new FileInputStream(annotaionInfoLoc + File.separator + "info.ser");
            ObjectInputStream ois = new ObjectInputStream(fis);
            try {
                studyAnnotaions.put(studyInstanceUid, (StudyAnnotation) ois.readObject());
            } catch (ClassNotFoundException ex) {
                System.out.println("Class not found");
            }
        } catch (IOException ex) {
//            System.out.println("IOE : " + ex.getMessage());
            //ignore
        }
    }

    public SeriesAnnotations getSeriesAnnotation(String studyInstanceUID, String seriesInstanceUID) {
        if (studyAnnotaions.get(studyInstanceUID) == null) {
            studyAnnotaions.put(studyInstanceUID, new StudyAnnotation());
        }
        if (studyAnnotaions.get(studyInstanceUID).getSeriesAnnotation(seriesInstanceUID) == null) {
            studyAnnotaions.get(studyInstanceUID).putSeriesAnnotation(seriesInstanceUID, new SeriesAnnotations(seriesInstanceUID));
        }
        return studyAnnotaions.get(studyInstanceUID).getSeriesAnnotation(seriesInstanceUID);
    }

    public void putSeriesAnnotation(String studyInstanceUID, String seriesInstanceUID, SeriesAnnotations seriesAnnotaion) {
        studyAnnotaions.get(studyInstanceUID).putSeriesAnnotation(seriesInstanceUID, seriesAnnotaion);
    }

    public StudyAnnotation getStudyAnnotaion(String studyUid) {
        return studyAnnotaions.get(studyUid);
    }
}
