/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.param.TextOverlayParam;
import java.awt.Graphics;

/**
 *
 * @author  BabuHussain
 * @version 0.5
 *
 */
public class TextOverlay extends javax.swing.JPanel {

    /** Creates new form DateFormatPanel */
    private TextOverlayParam textOverlayParam;
    LayeredCanvas layeredCanvas;
    private boolean firstTime = true;
    private boolean textOverlay = true;
    private boolean showProbeFlag = false;

    public TextOverlay(LayeredCanvas l) {
        initComponents();
        textOverlayParam = new TextOverlayParam();
        this.setOpaque(false);
        layeredCanvas = l;
    }

    public void setProbeParameters(String[] probeParameters) {
        textOverlayParam.setProbeParameters(probeParameters);
        this.showProbeFlag = true;
        this.repaint();
    }

    public void setWindowingParameter(String WL, String WW) {
        textOverlayParam.setWindowingParameter(WL, WW);
        this.repaint();
    }

    public TextOverlayParam getTextOverlayParam() {
        return textOverlayParam;
    }

    public void setTextOverlayParam(TextOverlayParam textOverlayParam) {
        this.textOverlayParam = textOverlayParam;
    }

    public void toggleTextOverlay() {
        if (textOverlay) {
            textOverlay = false;
            this.repaint();
        } else {
            textOverlay = true;
            this.repaint();
        }
    }

    public void updateCurrentInstanceNo(int currentInstanceNo) {
        textOverlayParam.setCurrentInstance(Integer.toString(currentInstanceNo));
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameLabel = new javax.swing.JLabel();
        patientSexLabel = new javax.swing.JLabel();
        patientIDLabel = new javax.swing.JLabel();
        huLabel = new javax.swing.JLabel();
        studyTimeLabel = new javax.swing.JLabel();
        studyDateLabel = new javax.swing.JLabel();
        institutionLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        patientPositionLabel = new javax.swing.JLabel();
        instanceNoLabel = new javax.swing.JLabel();
        windowingLabel = new javax.swing.JLabel();
        slicePositionLabel = new javax.swing.JLabel();
        zoomLabel = new javax.swing.JLabel();

        patientNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNameLabel.setText("Name");

        patientSexLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientSexLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientSexLabel.setText("Sex");

        patientIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientIDLabel.setText("ID");

        huLabel.setBackground(new java.awt.Color(0, 0, 0));
        huLabel.setForeground(new java.awt.Color(255, 255, 255));
        huLabel.setText("hu");

        studyTimeLabel.setBackground(new java.awt.Color(0, 0, 0));
        studyTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        studyTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studyTimeLabel.setText("Study Time");

        studyDateLabel.setBackground(new java.awt.Color(0, 0, 0));
        studyDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        studyDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studyDateLabel.setText("Study Date");

        institutionLabel.setBackground(new java.awt.Color(0, 0, 0));
        institutionLabel.setForeground(new java.awt.Color(255, 255, 255));
        institutionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        institutionLabel.setText("Institution");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        patientPositionLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientPositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientPositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patientPositionLabel.setText("Patient Position");

        instanceNoLabel.setBackground(new java.awt.Color(0, 0, 0));
        instanceNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        instanceNoLabel.setText("Im");

        windowingLabel.setBackground(new java.awt.Color(0, 0, 0));
        windowingLabel.setForeground(new java.awt.Color(255, 255, 255));
        windowingLabel.setText("Windowing");

        slicePositionLabel.setBackground(new java.awt.Color(0, 0, 0));
        slicePositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        slicePositionLabel.setText("Slice Position");

        zoomLabel.setBackground(new java.awt.Color(0, 0, 0));
        zoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        zoomLabel.setText("zoom");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(patientSexLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(patientIDLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(patientNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(147, 147, 147)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(studyTimeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, studyDateLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, institutionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(slicePositionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap(292, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(huLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .add(232, 232, 232))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(instanceNoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .add(232, 232, 232))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(windowingLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .add(275, 275, 275))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(zoomLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(252, 252, 252)
                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .add(patientPositionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(institutionLabel)
                    .add(patientNameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(patientSexLabel)
                            .add(patientIDLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 143, Short.MAX_VALUE)
                        .add(zoomLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(studyDateLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(studyTimeLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel8)
                    .add(huLabel))
                .add(8, 8, 8)
                .add(instanceNoLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(windowingLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(slicePositionLabel)
                    .add(patientPositionLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTextOverlay() {
        patientNameLabel.setText(" " + textOverlayParam.getPatientName() != null ? textOverlayParam.getPatientName() : "");
        patientIDLabel.setText("" + "ID: " + textOverlayParam.getPatientID());
        patientSexLabel.setText(" " + textOverlayParam.getSex() != null ? textOverlayParam.getSex() : "");
        patientPositionLabel.setText("Position: " + textOverlayParam.getPatientPosition() != null ? textOverlayParam.getPatientPosition() : "" + " ");
        studyDateLabel.setText("Study Date: " + textOverlayParam.getStudyDate() != null ? textOverlayParam.getStudyDate() : "" + " ");
        studyTimeLabel.setText("Study Time: " + textOverlayParam.getStudyTime() != null ? textOverlayParam.getStudyTime() : "" + " ");
        slicePositionLabel.setText(" " + "Slice pos: " + textOverlayParam.getSlicePosition() != null ? textOverlayParam.getSlicePosition() : "");

        if (ImagePanel.isProbeFlag()) {
            huLabel.setText(" " + "X:  " + textOverlayParam.getXPosition() + "  Y:  " + textOverlayParam.getYPosition() + "  Px:  " + textOverlayParam.getPxValue());
        } else {
            huLabel.setText("");
        }
        int currentInstanceNo = Integer.parseInt(textOverlayParam.getCurrentInstance()) + 1;
        int totalNo = Integer.parseInt(textOverlayParam.getTotalInstance());
        instanceNoLabel.setText(" " + "Im :" + currentInstanceNo + "/" + totalNo);
        institutionLabel.setText(textOverlayParam.getInstitutionName() != null ? textOverlayParam.getInstitutionName() : "" + " ");
        windowingLabel.setText(" " + "W " + textOverlayParam.getWindowWidth() + "/ C " + textOverlayParam.getWindowLevel());
        zoomLabel.setText(textOverlayParam.getZoomLevel());
    }

    private void setTextOverlayToNull() {
        patientNameLabel.setText("");
        patientIDLabel.setText("");
        patientSexLabel.setText("");
        patientPositionLabel.setText("");
        studyDateLabel.setText("");
        studyTimeLabel.setText("");
        slicePositionLabel.setText("");
        huLabel.setText("");
        instanceNoLabel.setText("");
        institutionLabel.setText("");
        windowingLabel.setText("");
        zoomLabel.setText("");

    }

    public void resizeHandler() {
        firstTime = true;
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (textOverlay) {
            setTextOverlay();
        } else {
            setTextOverlayToNull();
        }
        if (firstTime) {
            this.setSize(layeredCanvas.getSize().width, layeredCanvas.getSize().height);
            firstTime = false;
            repaint();
        }
        showProbeFlag = false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel huLabel;
    private javax.swing.JLabel instanceNoLabel;
    private javax.swing.JLabel institutionLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientPositionLabel;
    private javax.swing.JLabel patientSexLabel;
    private javax.swing.JLabel slicePositionLabel;
    private javax.swing.JLabel studyDateLabel;
    private javax.swing.JLabel studyTimeLabel;
    private javax.swing.JLabel windowingLabel;
    private javax.swing.JLabel zoomLabel;
    // End of variables declaration//GEN-END:variables
}
