<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svg="http://www.w3.org/2000/svg" xmlns:v="urn:schemas-microsoft-com:vml">
$headCommon()$
$! Need to check if controller is defined, as a ^R happens on key down, and the key up is delivered too early to be useful !$
<body onkeyup="if(typeof(controller)!=='undefined') return controller.keyPress(null, event);">
	$xeroBody()$
	
	$xeroScripts()$
</body>
</html>

