/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.delegate.AnnotationDelegate;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author  BabuHussain
 * @version 0.5
 *
 */
public class ImageView extends javax.swing.JFrame {

    /** Creates new form ImageView */
    String openedFilePath = "";
    public static boolean annotationAlreadyStored = false;

    public ImageView() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public ImageView(String openedFilePath) {
        this.openedFilePath = openedFilePath;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageToolbar1 = new in.raster.mayam.form.ImageToolbar(this);
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Image View");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/in/raster/mayam/form/images/fav_mayam.png")));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowCloseHandler(evt);
            }
        });

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setOpaque(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imageToolbar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
            .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(imageToolbar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowCloseHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowCloseHandler
        saveAnnotationOfTabs();
        ApplicationContext.imgView = null;
        if (LayoutManagerPanel.updateSeries) {
            if (LayoutManagerPanel.updatePropertiesDetails) {
                ApplicationContext.databaseRef.updatePropertiesDetail("true");
            } else {
                ApplicationContext.databaseRef.updatePropertiesDetail("false");
            }
            ApplicationContext.mainScreen.showThumbnails();
            LayoutManagerPanel.updateSeries = false;
        }
    }//GEN-LAST:event_windowCloseHandler
    public void saveAnnotationOfTabs() {
        imageToolbar1.resetCineTimer();
        if (!annotationAlreadyStored) {
            if (ApplicationContext.imgView != null && ApplicationContext.imgView.jTabbedPane1 != null) {
                int count = ApplicationContext.imgView.jTabbedPane1.getComponentCount();
                AnnotationDelegate annotationDelegate = new AnnotationDelegate();
                for (int x = 0; x < count; x++) {
                    annotationDelegate.storeAnnotationHook(x);
                    annotationDelegate.saveAnnotation(x);
                }
            }
        }
        annotationAlreadyStored = false;
    }
    public ImageToolbar getImageToolbar()
    {
        return this.imageToolbar1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ImageView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private in.raster.mayam.form.ImageToolbar imageToolbar1;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
