<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<results xmlns="http://www.dcm4chee.org/xero/search/study/" xmlns:ns2="http://www.w3.org/2000/svg" xmlns:ns3="http://www.w3.org/1999/xlink">
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Doe^Jane" PatientIdentifier="mypid" PatientID="27127">
<study xsi:type="studyBean" StudyDateF="4-Aug-2005 3:45:00 PM" gspsLabel="LCC" studyUID="1.2.752.24.7.1956254735.128761" StudyID="2" StudyDateTime="2005-08-04T15:45:00.000-04:00" NumberOfStudyRelatedSeries="10" NumberOfStudyRelatedInstances="17" ModalitiesInStudy="MG,PR,SR" InstanceAvailability="ONLINE" AccessionNumber="2">
</study>
<study xsi:type="studyBean" StudyDateF="25-Jul-2005 11:52:20 AM" gspsLabel="LCC" studyUID="1.2.124.113532.10.7.222.5.20050725.111627.1262683" StudyID="STUDY_ID" StudyDescription="STUDY_DESCRIPTION" StudyDateTime="2005-07-25T11:52:20.000-04:00" ReferringPhysicianName="REFERRING_PHYSICIAN" NumberOfStudyRelatedSeries="11" NumberOfStudyRelatedInstances="15" ModalitiesInStudy="MG,PR,SR" InstanceAvailability="ONLINE" AccessionNumber="ACCESSION_NUMBER">
</study>
</patient>
</results>
