BUILD INSTRUCTIONS FOR DCM4JBOSS-SAR:
====================================

In order to build dcm4jboss-sar you have to download and install:

- Ant 1.6.x (from http://ant.apache.org)

- JUnit 3.8.x (from http://junit.org)

- Jakarta Cactus 1.5 for J2EE 1.3 [http://jakarta.apache.org/cactus/]
(needed to build dcm4jboss-ejb, which itself required to build dcm4jboss-sar)

- XDoclet 1.2 [http://xdoclet.sourceforge.net]

- JBoss 3.2.3 [http://jboss.org]

Create an environment variable pointing to the Ant home directory (ANT_HOME)
and add the $ANT_HOME/bin directory to your PATH.

Copy junit.jar from the JUnit package into $ANT_HOME/lib/.

You need to build the dcm4che core library and the dcm4jboss-ejb 
components from the source, before you can build dcm4jboss-sar.

At first time, connecting to the project CVS repository, you have to login by

>cvs -d:pserver:anonymous@cvs.dcm4che.sourceforge.net:/cvsroot/dcm4che login
CVS password:<enter>


Download the source of the dcm4che core library by

>cvs -z3 -d:pserver:anonymous@cvs.dcm4che.sourceforge.net:/cvsroot/dcm4che
  checkout dcm4che14 

and build the library jar, by running

>ant jar

with the dcm4che14 distribution directory as working directory.

Download the source of the dcm4jboss-ejb package by

>cvs -z3 -d:pserver:anonymous@cvs.dcm4che.sourceforge.net:/cvsroot/dcm4che
  checkout dcm4jboss-ejb

The default build script (build.xml) assumes following locations of
components required for building dcm4jboss-ejb:

<!-- Override with your dcm4che dist location -->
<property name="dcm4che.home" value="../dcm4che14/build"/>		

<!-- Override with your XDoclet bundle dist location -->
<property name="xdoclet.home" value="${user.home}/xdoclet-1.2"/>

<!-- Override with your Cactus bundle dist location -->
<property name="cactus.home" value="${user.home}/jakarta-cactus-13-1.5"/>

<!-- Override with your JBoss/Web server bundle dist location -->
<property name="jboss.home" value="${user.home}/jboss-3.2.3"/>		

Instead of modifying the build script directly, you may adjust these values
to your build environment by renaming file build.properties.default to
build.properties and modify the values in it.

After that, invoking

>ant jar

with the dcm4jboss-ejb distribution directory as working directory
builds database specific ejb-jars and jars needed for EJB clients and
for direct DB access via JDBC.

The source of the dcm4jboss-sar package is available in module dcm4jboss-sar
in the dcm4che project CVS repository:

>cvs -z3 -d:pserver:anonymous@cvs.dcm4che.sourceforge.net:/cvsroot/dcm4che
  checkout dcm4jboss-sar

The default build script (build.xml) assumes following locations of
components required for building dcm4jboss-ejb:

<!-- Override with your dcm4che dist location -->
<property name="dcm4che.home" value="../dcm4che14/build"/>		

<!-- Override with your dcm4jboss-ejb dist location -->
<property name="dcm4jboss-ejb.home" value="../dcm4jboss-ejb"/>		

<!-- Override with your XDoclet bundle dist location -->
<property name="xdoclet.home" value="${user.home}/xdoclet-1.2"/>

<!-- Override with your JBoss/Web server bundle dist location -->
<property name="jboss.home" value="${user.home}/jboss-3.2.3"/>		

Instead of modifying the build script directly, you may adjust these values
to your build environment by renaming file build.properties.default to
build.properties and modify the values in it.

After that, invoking

>ant dist

with the dcm4jboss-sar distribution directory as working directory
generates the distribution package

target/dcm4jboss-<version>.zip
.
