<head>
  <meta http-equiv="Content-Type" content="text/xhtml"/>
  <meta content="initial-scale=1.0" name="viewport"/>
  <link type="text/css" rel="stylesheet" href="style/general.css"> </link>
  <link type="text/css" rel="stylesheet" href="local/style.css"> </link>
  <title>Xero Query</title>
  <script src="firebug/firebug.js" type="text/ecmascript" > </script>
  <script src="js/Events.js" type="text/ecmascript"> </script>
  <script src="js/sarissa.js" type="text/ecmascript"> </script>
  $head()$
  <script src="xeroModelController.js" type="text/ecmascript"> </script>
  <script>
/** Define per-user information as required TODO - move this to a child script */
xeroModel.userName = "$userName$";  
  </script>
</head>