<results xmlns="http://www.dcm4chee.org/xero/search/study/" xmlns:ns2="http://www.w3.org/2000/svg" xmlns:ns3="http://www.w3.org/1999/xlink">
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="VOI^LUT^PState^Test" PatientIdentifier="VLUT_Pnn" PatientID="VLUT_Pnn">
<study xsi:type="studyBean" StudyDateF="17-Nov-1999 8:30:40 AM" studyUID="1.2.276.0.7230010.3.200.4" StudyID="VLUT_Pnn" StudyDescription="VOI LUT PState Test" StudyDateTime="1999-11-17T08:30:40.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="13" NumberOfStudyRelatedInstances="24" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="1" seriesUID="1.2.276.0.7230010.3.200.4.1" SeriesDescription="8 in 8,range 0 to +255,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.1.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="2" seriesUID="1.2.276.0.7230010.3.200.4.2" SeriesDescription="8 in 8,range 0 to +255,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.2.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="3" seriesUID="1.2.276.0.7230010.3.200.4.3" SeriesDescription="8 in 8,range 25 to 75,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.3.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="4" seriesUID="1.2.276.0.7230010.3.200.4.4" SeriesDescription="8 in 8,range 0 to +255,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.4.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="5" seriesUID="1.2.276.0.7230010.3.200.4.5" SeriesDescription="8 in 8,range 0 to +255,unsigned,mono1,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.5.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="6" seriesUID="1.2.276.0.7230010.3.200.4.6" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.6.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="7" seriesUID="1.2.276.0.7230010.3.200.4.7" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.7.1" Position="0" InstanceNumber="1" minPixel="-2048.0" windowExplanation="" maxPixel="2048.0" windowCenter="0.0" windowWidth="4096.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="8" seriesUID="1.2.276.0.7230010.3.200.4.8" SeriesDescription="12 in 16,range 25 to 74,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.8.1" Position="0" InstanceNumber="1" minPixel="-2048.0" windowExplanation="" maxPixel="2048.0" windowCenter="50.0" windowWidth="50.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="9" seriesUID="1.2.276.0.7230010.3.200.4.9" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.9.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="10" seriesUID="1.2.276.0.7230010.3.200.4.10" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono1,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.10.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="11" seriesUID="1.2.276.0.7230010.3.200.4.11" SeriesDescription="inappropriate voi lut transform" Modality="OT">
<image xsi:type="imageBean" gspsUID="1.2.276.0.7230010.3.200.4.0.11" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.11.1" Position="0" InstanceNumber="1" windowExplanation="NONE" windowCenter="50.5" windowWidth="51.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="12" seriesUID="1.2.276.0.7230010.3.200.4.12" SeriesDescription="inappropriate voi lut transform" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.4.12.1" Position="0" InstanceNumber="1" minPixel="0.0" windowExplanation="" maxPixel="256.0" windowCenter="0.0" windowWidth="128.0">
</image>
</series>
<series xsi:type="seriesBean" seriesUID="PR:1.2.276.0.7230010.3.200.4" Modality="PR">
<gsps presentationDateTime="1999-11-17T08:30:40.000-05:00" contentLabel="VLUT_P01" objectUID="1.2.276.0.7230010.3.200.4.0.1">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:42.000-05:00" contentLabel="VLUT_P02" objectUID="1.2.276.0.7230010.3.200.4.0.2">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:43.000-05:00" contentLabel="VLUT_P03" objectUID="1.2.276.0.7230010.3.200.4.0.3">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:45.000-05:00" contentLabel="VLUT_P04" objectUID="1.2.276.0.7230010.3.200.4.0.4">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:46.000-05:00" contentLabel="VLUT_P05" objectUID="1.2.276.0.7230010.3.200.4.0.5">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:48.000-05:00" contentLabel="VLUT_P06" objectUID="1.2.276.0.7230010.3.200.4.0.6">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:49.000-05:00" contentLabel="VLUT_P07" objectUID="1.2.276.0.7230010.3.200.4.0.7">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:51.000-05:00" contentLabel="VLUT_P08" objectUID="1.2.276.0.7230010.3.200.4.0.8">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:53.000-05:00" contentLabel="VLUT_P09" objectUID="1.2.276.0.7230010.3.200.4.0.9">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:55.000-05:00" contentLabel="VLUT_P10" objectUID="1.2.276.0.7230010.3.200.4.0.10">
</gsps>
<gsps presentationDateTime="2000-06-28T12:00:00.000-04:00" contentLabel="VLUT_P11" objectUID="1.2.276.0.7230010.3.200.4.0.11">
</gsps>
<gsps presentationDateTime="2000-06-28T12:00:00.000-04:00" contentLabel="VLUT_P12" objectUID="1.2.276.0.7230010.3.200.4.0.12">
</gsps>
</series>
<series xsi:type="seriesBean" SeriesNumber="0" seriesUID="1.2.276.0.7230010.3.200.4.0" SeriesDescription="pstates for voi lut pstate test" Modality="PR">
</series>
</study>
</patient>
</results>
