-- Update DB from dcm4chee-2.10.x to dcm4chee-2.11.x

CREATE TABLE other_pat_id (
	pk              SERIAL NOT NULL CONSTRAINT other_pat_id_pk PRIMARY KEY,
	patient_fk      INTEGER,
	pat_id         	TEXT NOT NULL,
	pat_id_issuer  	TEXT,
	pat_id_type  	TEXT,
FOREIGN KEY (patient_fk) REFERENCES patient(pk)
);
CREATE INDEX other_pat_id_fk ON other_pat_id(patient_fk);
CREATE INDEX other_pat_id_ix ON other_pat_id(pat_id, pat_id_issuer);
CREATE INDEX other_pat_id_type ON other_pat_id(pat_id_type);
