-- Update DB from dcm4chee-2.12.x to dcm4chee-2.13.x

DROP TABLE study_permission;
CREATE TABLE study_permission (
	pk              SERIAL NOT NULL CONSTRAINT study_permission_pk PRIMARY KEY,
	study_iuid      TEXT NOT NULL,
	action          TEXT NOT NULL,
	roles           TEXT NOT NULL
);
CREATE UNIQUE INDEX study_perm_idx ON study_permission(study_iuid, action, roles);

INSERT INTO roles VALUES('admin','Doctor');
INSERT INTO roles VALUES('user','Doctor');
