function XeroRootMenu(suffix) {
	this.baseConstructor("XeroRootMenu");
	if(!suffix) suffix="";
$layout/addChildren(children=overallMenuLayout.children)$
};

XeroRootMenu.prototype = new Layout("XeroRootMenuPrototype","html/menu");
XeroRootMenu.prototype.baseConstructor = Layout;
XeroRootMenu.prototype.displayClass="rootMenu menu";

function UserNameMenu(suffix) {
	this.baseConstructor("UserNameMenu");
	$layout/addChildren(children=userMenuLayout.children)$
};

UserNameMenu.prototype = new Layout("XeroRootMenuPrototype","html/userName");

