<?xml version="1.0" encoding="UTF-8" ?>

<!--**************************************************************************
 *                                                                           *
 *  Copyright (c) 2001,2002 by TIANI MEDGRAPH AG                             *
 *                                                                           *
 *  This file is part of dcm4che.                                            *
 *                                                                           *
 *  This library is free software; you can redistribute it and/or modify it  *
 *  under the terms of the GNU Lesser General Public License as published    *
 *  by the Free Software Foundation; either version 2 of the License, or     *
 *  (at your option) any later version.                                      *
 *                                                                           *
 *  This library is distributed in the hope that it will be useful, but      *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of               *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU        *
 *  Lesser General Public License for more details.                          *
 *                                                                           *
 *  You should have received a copy of the GNU Lesser General Public         *
 *  License along with this library; if not, write to the Free Software      *
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  *
 *                                                                           *
 ***************************************************************************-->

<!-- $Id -->

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>

<xsl:template match="/">
<xsl:text>
/*****************************************************************************
 *                                                                           *
 *  Copyright (c) 2001,2002 by TIANI MEDGRAPH AG                             *
 *                                                                           *
 *  This file is part of dcm4che.                                            *
 *                                                                           *
 *  This library is free software; you can redistribute it and/or modify it  *
 *  under the terms of the GNU Lesser General Public License as published    *
 *  by the Free Software Foundation; either version 2 of the License, or     *
 *  (at your option) any later version.                                      *
 *                                                                           *
 *  This library is distributed in the hope that it will be useful, but      *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of               *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU        *
 *  Lesser General Public License for more details.                          *
 *                                                                           *
 *  You should have received a copy of the GNU Lesser General Public         *
 *  License along with this library; if not, write to the Free Software      *
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  *
 *                                                                           *
 *****************************************************************************
 *  This file was automatically generated by XSLT from                       *
 *  src/etc/dictionary.xml applying stylesheet src/etc/Tags.xsl.             *
 *  Manually modifications will be lost with next auto generation. For       *
 *  permanent modification edit the XML source or/and the XSL stylesheet.    *
 *****************************************************************************/

package org.dcm4che.dict;

/** Provides tag constants.
 *
 * @author gunter zeilinger
 * @version 1.0
 */
public class Tags {

    /** Private constructor */
    private Tags() {
    }

    public static StringBuffer toHexString(StringBuffer sb, int v, int l) {
        String hex = Integer.toHexString(v);
        for (int i = hex.length(); i &lt; l; ++i)
            sb.append('0');
        sb.append(hex);
        return sb;
    }

    public static final int forName(String name)
    throws NoSuchFieldException {
       try {
          return UIDs.class.getField(name).getInt(null);
       } catch (IllegalAccessException e) {
          throw new Error(e);
       }
    }

    public static String toHexString(int v, int l) {
        return toHexString(new StringBuffer(l),v,l).toString();
    }

    public static StringBuffer toString(StringBuffer sb, int tag) {
        sb.append('(');
        toHexString(sb, tag >>> 16, 4).append(',');
        toHexString(sb, tag &amp; 0xffff, 4).append(')');
        return sb;        
    }

    public static String toString(int tag) {
        return toString(new StringBuffer(11),tag).toString();
    }    

</xsl:text>
<xsl:apply-templates select="dictionary/elements/element"/>
<xsl:text>}</xsl:text>
</xsl:template>

<xsl:template match="element">
<xsl:text>    /** </xsl:text><xsl:value-of select="@tag"/>
<xsl:text> VR=</xsl:text><xsl:value-of select="@vr"/>
<xsl:text> </xsl:text><xsl:value-of select="@name"/>
<xsl:text> */
    public static final int </xsl:text><xsl:value-of select="@key"/>
<xsl:text> = 0x</xsl:text>
<xsl:value-of select="translate(substring(@tag,2,4),'x0123456789ABCDEF','00123456789ABCDEF')"/>
<xsl:value-of select="translate(substring(@tag,7,4),'x0123456789ABCDEF','00123456789ABCDEF')"/>
<xsl:text>;

</xsl:text>
</xsl:template>

</xsl:stylesheet>