<?xml version="1.0" encoding="UTF-8" ?>

<!--**************************************************************************
 *                                                                           *
 *  Copyright (c) 2001,2002 by TIANI MEDGRAPH AG                             *
 *                                                                           *
 *  This file is part of dcm4che.                                            *
 *                                                                           *
 *  This library is free software; you can redistribute it and/or modify it  *
 *  under the terms of the GNU Lesser General Public License as published    *
 *  by the Free Software Foundation; either version 2 of the License, or     *
 *  (at your option) any later version.                                      *
 *                                                                           *
 *  This library is distributed in the hope that it will be useful, but      *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of               *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU        *
 *  Lesser General Public License for more details.                          *
 *                                                                           *
 *  You should have received a copy of the GNU Lesser General Public         *
 *  License along with this library; if not, write to the Free Software      *
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  *
 *                                                                           *
 ***************************************************************************-->

<!-- $Id -->

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>

<xsl:template match="/">
<xsl:text>
/*****************************************************************************
 *                                                                           *
 *  Copyright (c) 2001,2002 by TIANI MEDGRAPH AG                             *
 *                                                                           *
 *  This file is part of dcm4che.                                            *
 *                                                                           *
 *  This library is free software; you can redistribute it and/or modify it  *
 *  under the terms of the GNU Lesser General Public License as published    *
 *  by the Free Software Foundation; either version 2 of the License, or     *
 *  (at your option) any later version.                                      *
 *                                                                           *
 *  This library is distributed in the hope that it will be useful, but      *
 *  WITHOUT ANY WARRANTY; without even the implied warranty of               *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU        *
 *  Lesser General Public License for more details.                          *
 *                                                                           *
 *  You should have received a copy of the GNU Lesser General Public         *
 *  License along with this library; if not, write to the Free Software      *
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  *
 *                                                                           *
 *****************************************************************************
 *  This file was automatically generated by XSLT from                       *
 *  src/etc/dictionary.xml applying stylesheet src/etc/UIDs.xsl.             *
 *  Manually modifications will be lost with next auto generation. For       *
 *  permanent modification edit the XML source or/and the XSL stylesheet.    *
 *****************************************************************************/

package org.dcm4che.dict;

/** Provides UIDs constants.
 *
 * @author gunter zeilinger
 * @version 1.0
 */
public class UIDs {

  /** Private constructor */
  private UIDs() {
  }

  public static final String forName(String name)
  throws NoSuchFieldException {
    try {
      return (String)UIDs.class.getField(name).get(null);
    } catch (IllegalAccessException e) {
      throw new Error(e);
    }
  }    

</xsl:text>
<xsl:apply-templates select="dictionary/uids/uid"/>
<xsl:text>}</xsl:text>
</xsl:template>

<xsl:template match="uid">
<xsl:text>  /** </xsl:text><xsl:value-of select="../@type"/>
<xsl:text>: </xsl:text><xsl:value-of select="@name"/><xsl:text> */
  public static final String </xsl:text><xsl:value-of select="@key"/>
<xsl:text> = "</xsl:text><xsl:value-of select="@value"/>
<xsl:text>";

</xsl:text>
</xsl:template>

</xsl:stylesheet>