<line x1="0" y1="0" x2="1000" y2="0" style="stroke: #202020; stroke-width: 4;" />
<line x1="0" y1="0" x2="0" y2="1000" style="stroke: #202020; stroke-width: 4;" />
<line x1="1000" y1="0" x2="1000" y2="1000" style="stroke: #202020; stroke-width: 4;" />
<line x1="0" y1="1000" x2="1000" y2="1000" style="stroke: #202020; stroke-width: 4;" />
$layout.image.use:{
$if(it.isDISPLAYREL)$<svg:use id="$it.id$" xlink:href="$it.href$" />$endif$
}$
