grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "LoginAllowed"
{
// DOC: swarm.principal.LoginAllowed
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "FolderRead"
{
// DOC: swarm.principal.FolderRead
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.StudyListPage", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "FolderWrite"
{
// DOC: swarm.principal.FolderWrite
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.ExportPage", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.MoveEntitiesPage", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.WadoImagePage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.folder.StudyPermissionsPage", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.StudyPermissionsPage:studypermissions:changeStudyPermissionAssignmentCheckbox", "render";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:mpps2MwlLinkWindow", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:imageSelectionWindow", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:wadoImageWindow", "render, enable";
// Permissions for edit patient
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:editPatientLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:studyPermissionsPatientLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:addStudyLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:webviewerPatientLink", "render, enable";
// Permissions for edit study
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:editStudyLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:studyPermissionsStudyLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:addSeriesLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:imageSelectionStudyLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:webviewerStudyLink", "render, enable";
// Permissions for edit pps
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:editPPSLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:linkPPSLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:unlinkPPSLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:emulatePPSLink", "render, enable";
// Permissions for edit series
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:editSeriesLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:imageSelectionSeriesLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:webviewerSeriesLink", "render, enable";
// Permissions for edit instance
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:editInstanceLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:webviewerInstanceLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:wadoImageInstanceLink", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "StudyPermissionsWrite"
{
// DOC: swarm.principal.StudyPermissionsWrite
    permission ${ComponentPermission} "org.dcm4chee.web.war.folder.StudyPermissionsPage:studypermissions:changeStudyPermissionAssignmentCheckbox", "enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "FolderActions"
{
// DOC: swarm.principal.FolderActions
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:deleteButton", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:moveButton", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:folder:exportButton", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "TrashRead"
{
// DOC: swarm.principal.TrashRead
    permission ${ComponentPermission} "org.dcm4chee.web.war.trash.TrashListPage", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "TrashActions"
{
// DOC: swarm.principal.TrashActions
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:trash:restoreButton", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:trash:deleteAllButton", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:trash:deleteButton", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "AERead"
{
// DOC: swarm.principal.AERead
    permission ${ComponentPermission} "org.dcm4chee.web.war.ae.AEListPanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "AEWrite"
{
// DOC: swarm.principal.AEWrite
    permission ${ComponentPermission} "org.dcm4chee.web.war.ae.CreateOrEditAETPage", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.ae.DicomEchoWindow$DicomEchoPage", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:ae:dicomEchoWindow", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:ae:dicomEchoLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:ae:newAETLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:ae:editAETLink", "render, enable";
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:ae:removeAETLink", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "UserRead"
{
// DOC: swarm.principal.UserRead
	permission ${ComponentPermission} "org.dcm4chee.usr.ui.usermanagement.user.UserListPanel", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:userlist:changeRoleAssignmentCheckbox", "render";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "UserWrite" 
{
// DOC: swarm.principal.UserWrite
	permission ${ComponentPermission} "org.dcm4chee.usr.ui.usermanagement.user.AddUserPage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:userlist:newUserLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:userlist:changePasswordLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:userlist:removeUserLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:userlist:changeRoleAssignmentCheckbox", "enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "RoleRead"
{
// DOC: swarm.principal.RoleRead
	permission ${ComponentPermission} "org.dcm4chee.usr.ui.usermanagement.role.RoleListPanel", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:rolelist:changePrincipalAssignmentCheckbox", "render";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "RoleWrite"
{
// DOC: swarm.principal.RoleWrite
	permission ${ComponentPermission} "org.dcm4chee.usr.ui.usermanagement.role.CreateOrEditRolePage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:rolelist:newRoleLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:rolelist:editRoleLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:rolelist:removeRoleLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:rolelist:changePrincipalAssignmentCheckbox", "enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "Dashboard"
{
// DOC: swarm.principal.Dashboard
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.DashboardPanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "FileSystem"
{
// DOC: swarm.principal.FileSystem
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.filesystem.FileSystemPanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "ReportRead"
{
// DOC: swarm.principal.ReportRead
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.report.ReportPanel", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.report.ConfigureReportPage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:DisplayDiagramLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:DisplayTableLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:DisplayDiagramAndTableLink", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "ReportWrite"
{
// DOC: swarm.principal.ReportWrite
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.report.CreateGroupPage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.report.CreateOrEditReportPage", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:newGroupLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:CreateOrEditReportLink", "render, enable";
	permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:report:RemoveLink", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "SystemInfo"
{
// DOC: swarm.principal.SystemInfo
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.systeminfo.SystemInfoPanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "Queue"
{
// DOC: swarm.principal.Queue
	permission ${ComponentPermission} "org.dcm4chee.dashboard.ui.messaging.QueuePanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "MWLRead"
{
// DOC: swarm.principal.MWLRead
    permission ${ComponentPermission} "org.dcm4chee.web.war.worklist.modality.ModalityWorklistPanel", "render, enable";
};

grant principal org.apache.wicket.security.hive.authorization.SimplePrincipal "MWLWrite"
{
// DOC: swarm.principal.MWLWrite
    permission ${ComponentPermission} "org.dcm4chee.web.war.MainPage:mw:editMwlItem", "render, enable";
};
