/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 *
 * The Initial Developer of the Original Code is
 * Raster Images
 * Portions created by the Initial Developer are Copyright (C) 2009-2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Babu Hussain A
 * Devishree V
 * Meer Asgar Hussain B
 * Prakash J
 * Suresh V
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
package in.raster.mayam.form;

import in.raster.mayam.context.ApplicationContext;
import in.raster.mayam.param.TextOverlayParam;
import java.awt.Graphics;

/**
 *
 * @author BabuHussain
 * @version 0.5
 *
 */
public class TextOverlay extends javax.swing.JPanel {

    /**
     * Creates new form DateFormatPanel
     */
    private TextOverlayParam textOverlayParam;
    LayeredCanvas layeredCanvas;
    private boolean firstTime = true;
    private boolean textOverlay = true;
    private boolean showProbeFlag = false;

    public TextOverlay(LayeredCanvas l) {
        initComponents();
        textOverlayParam = new TextOverlayParam();
        this.setOpaque(false);
        layeredCanvas = l;
    }

    public void setProbeParameters(String[] probeParameters) {
        textOverlayParam.setProbeParameters(probeParameters);
        this.showProbeFlag = true;
        this.repaint();
    }

    public void setWindowingParameter(String WL, String WW) {
        textOverlayParam.setWindowingParameter(WL, WW);
        this.repaint();
    }

    public TextOverlayParam getTextOverlayParam() {
        return textOverlayParam;
    }

    public void setTextOverlayParam(TextOverlayParam textOverlayParam) {
        this.textOverlayParam = textOverlayParam;
    }

    public void toggleTextOverlay() {
        if (textOverlay) {
            textOverlay = false;
            this.repaint();
        } else {
            textOverlay = true;
            this.repaint();
        }
    }

    public void updateCurrentInstanceNo(int currentInstanceNo) {
        textOverlayParam.setCurrentInstance(currentInstanceNo);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNameLabel = new javax.swing.JLabel();
        patientSexLabel = new javax.swing.JLabel();
        patientIDLabel = new javax.swing.JLabel();
        huLabel = new javax.swing.JLabel();
        studyDescLabel = new javax.swing.JLabel();
        studyDateLabel = new javax.swing.JLabel();
        institutionLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        patientPositionLabel = new javax.swing.JLabel();
        instanceNoLabel = new javax.swing.JLabel();
        windowingLabel = new javax.swing.JLabel();
        slicePositionLabel = new javax.swing.JLabel();
        zoomLabel = new javax.swing.JLabel();
        seriesDescLabel = new javax.swing.JLabel();
        viewSizeLabel = new javax.swing.JLabel();
        imageSizeLabel = new javax.swing.JLabel();
        multiframeStatusText = new javax.swing.JLabel();

        patientNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        patientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientNameLabel.setText("Name");

        patientSexLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientSexLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        patientSexLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientSexLabel.setText("Sex");

        patientIDLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        patientIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientIDLabel.setText("ID");

        huLabel.setBackground(new java.awt.Color(0, 0, 0));
        huLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        huLabel.setForeground(new java.awt.Color(255, 255, 255));
        huLabel.setText("hu");

        studyDescLabel.setBackground(new java.awt.Color(0, 0, 0));
        studyDescLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        studyDescLabel.setForeground(new java.awt.Color(255, 255, 255));
        studyDescLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studyDescLabel.setText("Study Desc");

        studyDateLabel.setBackground(new java.awt.Color(0, 0, 0));
        studyDateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        studyDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        studyDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studyDateLabel.setText("Study Date");

        institutionLabel.setBackground(new java.awt.Color(0, 0, 0));
        institutionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        institutionLabel.setForeground(new java.awt.Color(255, 255, 255));
        institutionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        institutionLabel.setText("Institution");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        patientPositionLabel.setBackground(new java.awt.Color(0, 0, 0));
        patientPositionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        patientPositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientPositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patientPositionLabel.setText("Patient Position");

        instanceNoLabel.setBackground(new java.awt.Color(0, 0, 0));
        instanceNoLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        instanceNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        instanceNoLabel.setText("Im");

        windowingLabel.setBackground(new java.awt.Color(0, 0, 0));
        windowingLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        windowingLabel.setForeground(new java.awt.Color(255, 255, 255));
        windowingLabel.setText("Windowing");

        slicePositionLabel.setBackground(new java.awt.Color(0, 0, 0));
        slicePositionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        slicePositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        slicePositionLabel.setText("Slice Position");

        zoomLabel.setBackground(new java.awt.Color(0, 0, 0));
        zoomLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        zoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        zoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zoomLabel.setText("Zoom");

        seriesDescLabel.setBackground(new java.awt.Color(0, 0, 0));
        seriesDescLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        seriesDescLabel.setForeground(new java.awt.Color(255, 255, 255));
        seriesDescLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seriesDescLabel.setText("Series Desc");

        viewSizeLabel.setBackground(new java.awt.Color(0, 0, 0));
        viewSizeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        viewSizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        viewSizeLabel.setText("View Size");

        imageSizeLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageSizeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        imageSizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imageSizeLabel.setText("Image Size");

        multiframeStatusText.setBackground(new java.awt.Color(255, 255, 153));
        multiframeStatusText.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        multiframeStatusText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        multiframeStatusText.setText("Multiframe");
        multiframeStatusText.setOpaque(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, instanceNoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, patientNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, patientIDLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, huLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, windowingLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, slicePositionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, patientSexLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(92, 92, 92))
                            .add(layout.createSequentialGroup()
                                .add(seriesDescLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(20, 20, 20))
                            .add(layout.createSequentialGroup()
                                .add(studyDescLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, studyDateLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, institutionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, viewSizeLabel)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, imageSizeLabel)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, zoomLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, patientPositionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(multiframeStatusText)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientNameLabel)
                    .add(institutionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientIDLabel)
                    .add(studyDateLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(patientSexLabel)
                    .add(studyDescLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(seriesDescLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel8)
                        .add(9, 9, 9)
                        .add(multiframeStatusText)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(imageSizeLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(viewSizeLabel))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(huLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(instanceNoLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(windowingLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(zoomLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(slicePositionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(patientPositionLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setTextOverlay() {
        patientNameLabel.setText(" " + textOverlayParam.getPatientName() != null ? textOverlayParam.getPatientName() : "");
        patientIDLabel.setText("" + ApplicationContext.currentBundle.getString("ImageView.textOverlay.patientIdLabel.text") + textOverlayParam.getPatientID());
        if (textOverlayParam.getSex() != null && !textOverlayParam.getSex().equalsIgnoreCase("")) {
            patientSexLabel.setText(ApplicationContext.currentBundle.getString("ImageView.textOverlay.patientSexLabel.text") + textOverlayParam.getSex());
        } else {
            patientSexLabel.setText("");
        }
        patientPositionLabel.setText(textOverlayParam.getPatientPosition() != null ? ApplicationContext.currentBundle.getString("ImageView.textOverlay.positionLabel.text") + textOverlayParam.getPatientPosition() : "" + " ");
        studyDateLabel.setText("Study Date: " + textOverlayParam.getStudyDate() != null ? textOverlayParam.getStudyDate() : "" + " ");
        studyDescLabel.setText("Study Desc: " + textOverlayParam.getStudyDescription() != null ? textOverlayParam.getStudyDescription() : "");
        seriesDescLabel.setText("Series Desc: " + textOverlayParam.getSeriesDescription() != null ? textOverlayParam.getSeriesDescription() : "");
        slicePositionLabel.setText(textOverlayParam.getSlicePosition() != null ? ApplicationContext.currentBundle.getString("ImageView.textOverlay.slicePositionLabel.text") + textOverlayParam.getSlicePosition() : "");
        imageSizeLabel.setText(textOverlayParam.getImageSize() != null ? ApplicationContext.currentBundle.getString("ImageView.textOverlay.imageSizeLabel.text") + textOverlayParam.getImageSize() : "");
        viewSizeLabel.setText(textOverlayParam.getViewSize() != null ? ApplicationContext.currentBundle.getString("ImageView.textOverlay.viewSizeLabel.text") + textOverlayParam.getViewSize() : "");
        if (ImagePanel.isProbeFlag()) {
            huLabel.setText(" " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.probeX.text") + textOverlayParam.getXPosition() + " " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.probeY.text") + textOverlayParam.getYPosition() + " " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.probePx.text") + textOverlayParam.getPxValue());
        } else {
            huLabel.setText("");
        }
        int currentInstanceNo = textOverlayParam.getCurrentInstance() + 1;
        if (!textOverlayParam.isMultiframe()) {
            instanceNoLabel.setText(" " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.imageLabel.text") + currentInstanceNo + "/" + textOverlayParam.getTotalInstance());
        } else {
            instanceNoLabel.setText(" " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.frameLable.text") + currentInstanceNo + "/" + textOverlayParam.getTotalInstance());
        }
        institutionLabel.setText(textOverlayParam.getInstitutionName() != null ? textOverlayParam.getInstitutionName() : "" + " ");
        windowingLabel.setText(" " + ApplicationContext.currentBundle.getString("ImageView.textOverlay.windowWidth.text") + textOverlayParam.getWindowWidth() + ApplicationContext.currentBundle.getString("ImageView.textOverlay.windowCenter.text") + textOverlayParam.getWindowLevel());
        zoomLabel.setText(textOverlayParam.getZoomLevel());
        multiframeStatusText.setText(ApplicationContext.currentBundle.getString("ImageView.textOverlay.multiframeLabel.text"));
    }

    private void setTextOverlayToNull() {
        patientNameLabel.setText("");
        patientIDLabel.setText("");
        patientSexLabel.setText("");
        patientPositionLabel.setText("");
        studyDateLabel.setText("");
        studyDescLabel.setText("");
        seriesDescLabel.setText("");
        slicePositionLabel.setText("");
        imageSizeLabel.setText("");
        viewSizeLabel.setText("");
        huLabel.setText("");
        instanceNoLabel.setText("");
        institutionLabel.setText("");
        windowingLabel.setText("");
        zoomLabel.setText("");
    }

    public void resizeHandler() {
        firstTime = true;
        repaint();
    }

    public void multiframeStatusDisplay(boolean status) {
        multiframeStatusText.setVisible(status);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (textOverlay) {
            setTextOverlay();
        } else {
            setTextOverlayToNull();
        }
        if (firstTime) {
            this.setSize(layeredCanvas.getSize().width, layeredCanvas.getSize().height);
            firstTime = false;
            setTextOverlayToNull();
            repaint();
        }
        showProbeFlag = false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel huLabel;
    private javax.swing.JLabel imageSizeLabel;
    private javax.swing.JLabel instanceNoLabel;
    private javax.swing.JLabel institutionLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel multiframeStatusText;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel patientPositionLabel;
    private javax.swing.JLabel patientSexLabel;
    private javax.swing.JLabel seriesDescLabel;
    private javax.swing.JLabel slicePositionLabel;
    private javax.swing.JLabel studyDateLabel;
    private javax.swing.JLabel studyDescLabel;
    private javax.swing.JLabel viewSizeLabel;
    private javax.swing.JLabel windowingLabel;
    private javax.swing.JLabel zoomLabel;
    // End of variables declaration//GEN-END:variables
}
