$markup:{
$it.svg:{
<svg:svg width="0" height="0">
$it.g:{
<svg:g id="$it.id$" stroke="$it.stroke$" fill="$it.fill$">
$it.image:{
<svg:image id="$it.id$" xlink:href="$it.href; format="xml"$" width="$it.width$" height="$it.height$" />
}$ 
$it.text:{
<svg:text id="$it.id$" transform="$it.transform$" font-size="$it.("font-size")$" textLength="$it.textLength$" x="$it.x$" y="$it.y$">
$it.TEXT; format="xml"$
</svg:text>
}$
$it.path:{
<svg:path id="$it.id$" stroke-width="$it.("stroke-width")$" fill="$it.fill$" d="$it.d$" />
}$
</svg:g>
}$
</svg:svg>
}$
}$
