<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<results xmlns="http://www.dcm4chee.org/xero/search/study/" xmlns:ns2="http://www.w3.org/2000/svg" xmlns:ns3="http://www.w3.org/1999/xlink">
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Modality^LUT^PState^Test" PatientIdentifier="MLUT_Pnn" PatientID="MLUT_Pnn">
<study xsi:type="studyBean" gspsLabel="MLUT_P20" StudyDateF="17-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.3" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P21" StudyDateF="18-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.4" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P22" StudyDateF="19-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.5" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
</patient>

<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Modality^LUT^PState^Test" PatientIdentifier="MLUT_Pnn" PatientID="MLUT_Pnn">
<study xsi:type="studyBean" gspsLabel="MLUT_P23" StudyDateF="20-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.6" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P24" StudyDateF="21-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.7" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P25" StudyDateF="22-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.8" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
</patient>

<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Modality^LUT^PState^Test" PatientIdentifier="MLUT_Pnn" PatientID="MLUT_Pnn">
<study xsi:type="studyBean" gspsLabel="MLUT_P26" StudyDateF="23-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.9" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P27" StudyDateF="24-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.10" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" gspsLabel="MLUT_P28" StudyDateF="25-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.11" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
</patient>
</results>
