$if(IS_IE)$
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svg="http://www.w3.org/2000/svg" xmlns:v="urn:schemas-microsoft-com:vml">
   <head>
      <meta http-equiv="Content-Type" content="text/xhtml"/>
      <title>Display Area Tests</title>
      <style type="text/css">
    v\:* { behavior: url(#default#VML); display: inline-block; overflow: hidden; position: absolute;  }

    </style>
    <!-- <script type='text/javascript' src='http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js'></script> -->

   </head>

<body style="margin: 0;width:100%; height:99%; overflow: hidden; background: red; position: absolute;">

   <div style="width:100%; height:18px; overflow: hidden; background: red;">
Section 1
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: green;">
Section 2
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: white;">
Section 3
   </div>
   <div style="width:100%; height:85%; overflow: hidden;">
      <div style="width:14.99%; height:100%; overflow: auto; background: blue; float: left;">
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>

<v:shapetype id="g1"
   fillcolor="#00FFFF" strokecolor="#FF00FF"
>
   <v:path v="m 125,125 l 125,135, 135,135, 135,125 x e"/>
   </v:shapetype>

   <v:shapetype id="t2147483740" coordsize="1000 1000" filled = "f" stroked = "f" path="m 125,125 l275,124">
          <v:textbox style="COLOR: white">Text in bounding box of correct size</v:textbox> 
   </v:shapetype>

<!-- expression((scaleToFitBox.clientWidth-Math.min(scaleToFitBox.clientWidth,scaleToFitBox.clientHeight))/2+'px') -->

</div>
      <div style="width:70%; height:100%; overflow: hidden; background: yellow; float: left;">
         <div id="scaleToFitBox" style="width:49.999%; height:50%; overflow: hidden; background: orange; float: left;" >
          <v:group id="scaleToFit" style="left: 9.6%; width: expression(Math.min(scaleToFitBox.clientWidth,scaleToFitBox.clientHeight));height: expression(Math.min(scaleToFitBox.clientWidth,scaleToFitBox.clientHeight)); "  coordorigin="0,0" coordsize="300,300">
            <v:rect style="width:300; height:300;" fillcolor="black"/>
            <v:rect style="left:100; top: 100; width:100; height:100;" fillcolor="blue" strokecolor="red" />
            <v:shape type="#g1" style="width:100%; height: 100%" coordsize="300 300"/>

            <v:line from="12,12" to="300,12" style="height: 15; width: 276;" filled='t' stroked='t' fillcolor="white" strokecolor="white">
               <v:path textpathok="True"/>
               <v:textpath on="True" string="Normal text at the upper border" style="font-size: 15px;"/>
            </v:line>
            <v:line from="288,12" to="288,288" style="height: 15; width: 100%;" filled='t' stroked='t' fillcolor="white" strokecolor="white">
               <v:path textpathok="True"/>
               <v:textpath on="True" string="Right rotated text at the right border." style="font-size: 15px;"/>
            </v:line>
            <v:line from="288,288" to="12,288" style="height: 15; width: 276;" filled='t' stroked='t' fillcolor="white" strokecolor="white">
               <v:path textpathok="True"/>
               <v:textpath on="True" string="Up-side down text at the lower border." style="font-size: 15px;"/>
            </v:line>
            <v:line from="12,288" to="12,12" style="height: 15; width: 100%;" filled='t' stroked='t' fillcolor="white" strokecolor="white">
               <v:path textpathok="True"/>
               <v:textpath on="True" string="Left rotated text at the left border." style="font-size: 15px;"/>
            </v:line>
          </v:group>

          <v:group style="width:100%; height:100%; left:0; top: 0;" coordorigin="0,0" coordsize="1000,1000">
            <v:rect style="width:100; height:100;" fillcolor="gray"/>
            <v:rect style="top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:shape style="left:100; top: 800; width:800; height: 100;" filled="f" stroked="f">
               <v:textbox style="color:white;">Scale to Fit - full image area.</v:textbox>
            </v:shape>
          </v:group>
         </div>
         <div style="width:50%; height:50%; overflow: hidden; background: cyan; float: left;">
          <v:group style="width:150px;height: 150px; left: -75px; margin-left:50%; top: 50%; margin-top: -75px;"  coordorigin="0,0" coordsize="300,300">
            <v:rect style="width:300; height:300;" fillcolor="black"/>
            <v:rect style="left:100; top: 100; width:100; height:100;" fillcolor="blue" strokecolor="red" />
            <v:shape type="#g1" style="width:100%; height: 100%"  coordsize="300 300"/>
           </v:group>

           <v:group style="width:100%; height:100%; left:0px;top:0px;;" coordorigin="0,0" coordsize="1000,1000">
            <v:rect style="width:100; height:100;" fillcolor="gray"/>
            <v:rect style="top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left:100; top: 800; width:800; height: 100;" filled="f" stroked="f">
               <v:textbox style="color:white;">Magnify Example - full area, m=0.5.</v:textbox>
            </v:rect>
           </v:group>
         </div>
         <div id="scaleToFitRBox" style="width:49.999%; height:50%; overflow: hidden; background: pink; float: left;">
           <v:group style="left: 9.6%; width: expression(Math.min(scaleToFitRBox.clientWidth,scaleToFitRBox.clientHeight));height: expression(Math.min(scaleToFitRBox.clientWidth,scaleToFitRBox.clientHeight));" coordorigin="100,100" coordsize="100,100">
            <v:rect style="width:300; height:300;" fillcolor="black"/>
            <v:rect style="left:100; top: 100; width:100; height:100;" fillcolor="blue" strokecolor="red" />
            <v:shape type="#g1" style="width:100%; height: 100%"  coordsize="300 300"/>
           </v:group>

           <v:group style="width:100%; height:100%; left:0px;top:0px;;" coordorigin="0,0" coordsize="1000,1000">
            <v:rect style="width:100; height:100;" fillcolor="gray"/>
            <v:rect style="top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left:100; top: 800; width:800; height: 100;" filled="f" stroked="f">
               <v:textbox style="color:white;">Scale to Fit - center 100 square pixels</v:textbox>
            </v:rect>
           </v:group>
         </div>
         <div style="width:50%; height:50%; overflow: hidden; background: purple; float: left;">
          <v:group style="width:3cm;height: 3cm; left: -1.5cm; margin-left:50%; top: 50%; margin-top: -1.5cm;"  coordorigin="0,0" coordsize="300,300">
            <v:rect style="width:300; height:300;" fillcolor="black"/>
            <v:rect style="left:100; top: 100; width:100; height:100;" fillcolor="blue" strokecolor="red" />
            <v:shape type="#g1" style="width:100%; height: 100%" coordorigin="0,0" coordsize="300 300"/>
           </v:group>

           <v:group style="width:100%; height:100%; left:0px;top:0px;;" coordorigin="0,0" coordsize="1000,1000">
            <v:rect style="width:100; height:100;" fillcolor="gray"/>
            <v:rect style="top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left: 900; top: 900; width:100; height:100;" fillcolor="gray"/>
            <v:rect style="left:100; top: 800; width:800; height: 150;" filled="f" stroked="f">
               <v:textbox style="color:white;">True Size - 3cm x 3cm, center rect 1 cm square</v:textbox>
            </v:rect>
           </v:group>
         </div>
      </div>
      <div style="width:14.99%; height:100%; overflow: hidden; background: blue; float: left;">
         Right Series Tray
      </div>
   </div>
      <div style="width:100%; height:18px; overflow: hidden; background: white;">
Section 4
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: green;">
Section 5
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: red;">
Section 6
   </div>
</body>
</html>
$else$
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svg="http://www.w3.org/2000/svg" xmlns:v="urn:schemas-microsoft-com:vml">
   <head>
      <meta http-equiv="Content-Type" content="text/xhtml"/>
      <title>Display Area Tests</title>
      <style type="text/css">
.image {
}
      </style>
   </head>

<body style="margin: 0;width:100%; height:99%; overflow: hidden; background: red; position: absolute;">

   <div style="width:100%; height:18px; overflow: hidden; background: red;">
Section 1
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: green;">
Section 2
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: white;">
Section 3
   </div>
   <div style="width:100%; height:85%; overflow: hidden;">
   <div style="width:15%; height:100%; overflow: auto; background: blue; float: left;">
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
         Left study tray <br />
<p>This is a really long paragraph that should have to wrap somehow.  There is lots of text in it and it is more than 15% wide.  It isn't clear how to make this fit exactly, but it should work somehow.</p>
      </div>
      <div style="width:70%; height:100%; overflow: hidden; background: yellow; float: left;">
         <div style="width:49.999%; height:50%; overflow: hidden; background: orange; float: left; ">
           <svg class="image"  style="background: black;width:100%; height:100%;" xmlns="http://www.w3.org/2000/svg">
             <svg viewBox="0 0 300 300" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
                <rect width="300" height="300" style="fill:yellow;" />
                <rect width="100" height="100" x="100" y="100" style="fill:blue; stroke-width:4; stroke: red;" />
                <text x="12" y="12" font-size="15">Normal text at the upper border.</text>
             </svg>
             <svg style="width:100%; height:100%;" viewBox="0 0 1000 1000" preserveAspectRatio="none">
                 <rect x="0" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="0" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <text x="150" y="200" font-size="55">Scale To Fit Example - full area.</text>
             </svg>
           </svg>
         </div>
         <div style="width:50%; height:50%; overflow: hidden; background: cyan; float: left;">
           <svg style="width:100%; height:100%;" xmlns="http://www.w3.org/2000/svg">
             <svg x="-75px" y="-75px" style="width:100%; overflow: visible;"  preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">
             <svg x="50%" y="50%" width="150px" height="150px" viewBox="0 0 300 300" xmlns="http://www.w3.org/2000/svg">
                <rect width="300" height="300" style="fill:yellow;" />
                <rect width="100" height="100" x="100" y="100" style="fill:blue; stroke-width:4; stroke: red;" />
             </svg>
             </svg>

             <svg style="width:100%; height:100%;" viewBox="0 0 1000 1000" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
                 <rect x="0" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="0" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <text x="150" y="100" font-size="55">Magnify Example - full area, m=0.5.</text>
             </svg>
           </svg>
         </div>
         <div style="width:49.999%; height:50%; overflow: hidden; background: pink; float: left;">
           <svg class="image"  style="background: black;width:100%; height:100%;" xmlns="http://www.w3.org/2000/svg">
             <svg style="display: block;" viewBox="100 100 100 100" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
                <rect width="300" height="300" style="fill:yellow;" />
                <rect width="100" height="100" x="100" y="100" style="fill:blue; stroke-width:4; stroke: red;" />
             </svg>
             <svg style="width:100%; height:100%;" viewBox="0 0 1000 1000" preserveAspectRatio="none">
                 <rect x="0" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="0" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <text x="150" y="100" font-size="55">Scale To Fit Example - center 100 square pixels.</text>
             </svg>
           </svg>
         </div>
         <div style="width:50%; height:50%; overflow: hidden; background: purple; float: left;text-align: center;">
           <svg style="width:100%; height:100%;" xmlns="http://www.w3.org/2000/svg">
             <svg x="-1.5cm" y="-1.5cm" style="width:100%; overflow: visible;"  preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">
             <svg x="50%" y="50%" width="3cm" height="3cm" viewBox="0 0 300 300" xmlns="http://www.w3.org/2000/svg">
                <rect width="300" height="300" style="fill:yellow;" />
                <rect width="100" height="100" x="100" y="100" style="fill:blue; stroke-width:4; stroke: red;" />
             </svg>
             </svg>

             <svg style="width:100%; height:100%;" viewBox="0 0 1000 1000" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
                 <rect x="0" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="0" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="0" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <rect x="900" y="900" width="100" height="100" style="fill:green; stroke-width:4; stroke: gray;" />
                 <text x="150" y="100" font-size="55">True size Example - 3cm square with 1 cm blue center square.</text>
             </svg>
           </svg>
         </div>
      </div>
      <div style="width:15%; height:100%; overflow: hidden; background: blue; float: left;">
         Right Series Tray
      </div>
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: white;">
Section 4
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: green;">
Section 5
   </div>
   <div style="width:100%; height:18px; overflow: hidden; background: red;">
Section 6
   </div>
</body>
</html>
$endif$