<div style="float: left; width: 220px;">
  <span class="actionIcon" onclick="controller.findAction('$layout.id$');"><img id="FindImg" alt="Find" src="$i18n.FindIcon$?v=$version$" width="92" height="92" style="width:48px; height: 48px; vertical-align: middle;"/></span>
  <span class="actionIcon" onclick="controller.clearQuery('$layout.id$');"><img id="ClearFind" alt="Clear Find" src="$i18n.ClearFindIcon$?v=$version$" width="48" height="48" style="vertical-align: middle;" /></span>
</div>