<li><a class="userName toolItem" tabindex="-1" href="#">$userName$
$if(layout.layouts)$
$if(IS_IE6)$<div class="autoWidthMenu"><table cellspacing="0" cellpadding="0" border="0"><tr><td>$else$</a><div class="autoWidthMenu">$endif$
<ul>
$layout.layouts:{layout|$if(layout.used)$$(layout.template)()$$endif$}$
</ul>
$if(IS_IE6)$</td></tr></table></div></a>$else$</div>$endif$
$else$
</a>
$endif$
</li>