<head>
  <meta http-equiv="Content-Type" content="text/xhtml"/>
  <meta content="initial-scale=1.0" name="viewport"/>
  <link type="text/css" rel="stylesheet" href="/xview/style/general.css"> </link>
  <title>Xero Query</title>
  <script src="/xview/firebug/firebug.js" type="text/ecmascript" > </script>
  <script src="/xview/js/Events.js" type="text/ecmascript"> </script>
  <script src="/xview/js/sarissa.js" type="text/ecmascript"> </script>
  $head()$
  <script src="/xview/xeroModelController.js" type="text/ecmascript"> </script>
</head>