<html>
<head>
  <meta content="initial-scale=1.0" name="viewport"/>
  <link type="text/css" rel="stylesheet" href="/xview/style/general.css"/>
  <title>Xero Query</title>
  <script src="/xview/firebug/firebug.js" type="text/ecmascript" > </script>
  <script src="/xview/js/sarissa.js" type="text/ecmascript"> </script>
  <script src="/xview/xeroBody.js" type="text/ecmascript"> </script>
</head>
<body>
<div id="body" name="body">
	$xeroBody()$
</div>
</body>
</html>

