
package org.dcm4chee.xds.infoset.v30;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentRegistry_Service", targetNamespace = "urn:ihe:iti:xds-b:2007", wsdlLocation = "/wsdl/registry.wsdl")
public class DocumentRegistryServiceAlt
    extends Service
{

    private final static URL DOCUMENTREGISTRYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.dcm4chee.xds.infoset.v30.DocumentRegistryServiceAlt.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.dcm4chee.xds.infoset.v30.DocumentRegistryServiceAlt.class.getResource(".");
            url = new URL(baseUrl, "wsdl/registry.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/wsdl/registry.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTREGISTRYSERVICE_WSDL_LOCATION = url;
    }

    public DocumentRegistryServiceAlt(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentRegistryServiceAlt() {
        super(DOCUMENTREGISTRYSERVICE_WSDL_LOCATION, new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Service"));
    }

    /**
     * 
     * @return
     *     returns DocumentRegistryPortType12
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap12")
    public DocumentRegistryPortTypeAlt getDocumentRegistryPortSoap12() {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap12"), DocumentRegistryPortTypeAlt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentRegistryPortType12
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap12")
    public DocumentRegistryPortTypeAlt getDocumentRegistryPortSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap12"), DocumentRegistryPortTypeAlt.class, features);
    }

}
