<results xmlns="http://www.dcm4chee.org/xero/search/study/" xmlns:ns2="http://www.w3.org/2000/svg" xmlns:ns3="http://www.w3.org/1999/xlink">
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Modality^LUT^PState^Test" PatientIdentifier="MLUT_Pnn" PatientID="MLUT_Pnn">
<study xsi:type="studyBean" StudyDateF="17-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.3" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="1" seriesUID="1.2.276.0.7230010.3.200.3.1" SeriesDescription="8 in 8,range 0 to +255,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.1.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="2" seriesUID="1.2.276.0.7230010.3.200.3.2" SeriesDescription="8 in 8,range 128 to +255,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.2.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="256.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="3" seriesUID="1.2.276.0.7230010.3.200.3.3" SeriesDescription="12 in 16, range 0 to +4095, high zero, unsigned, mono2, no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.3.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="4096.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="4" seriesUID="1.2.276.0.7230010.3.200.3.4" SeriesDescription="12 in 16, range 0 to +4095, high zero, unsigned, mono2, no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.4.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="4096.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="5" seriesUID="1.2.276.0.7230010.3.200.3.5" SeriesDescription="12 in 16,range 0 to +4095,high bits ones,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.5.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="4096.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="6" seriesUID="1.2.276.0.7230010.3.200.3.6" SeriesDescription="12 in 16,range 0 to +4095,high bits ones,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.6.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="4096.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="7" seriesUID="1.2.276.0.7230010.3.200.3.7" SeriesDescription="15 in 16,range 0 to +32767,high zero,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.7.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="8" seriesUID="1.2.276.0.7230010.3.200.3.8" SeriesDescription="15 in 16,range 0 to +32767,high bits zero,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.8.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="9" seriesUID="1.2.276.0.7230010.3.200.3.9" SeriesDescription="12 in 16,range 0 to +65535,high bits ones,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.9.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="65536.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="10" seriesUID="1.2.276.0.7230010.3.200.3.10" SeriesDescription="16 in 16,range 1024 to +65535,unsigned,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.10.1" Position="0" InstanceNumber="1" minPixel="0.0" maxPixel="65536.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="11" seriesUID="1.2.276.0.7230010.3.200.3.11" SeriesDescription="12 in 16,range -2048 to +2047,high zero,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.11.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="12" seriesUID="1.2.276.0.7230010.3.200.3.12" SeriesDescription="12 in 16,range -2048 to +2047,high zero,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.12.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="13" seriesUID="1.2.276.0.7230010.3.200.3.13" SeriesDescription="16 in 16,range -32768 to +32767,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.13.1" Position="0" InstanceNumber="1" minPixel="-32768.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="14" seriesUID="1.2.276.0.7230010.3.200.3.14" SeriesDescription="16 in 16,range -32768 to +32767,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.14.1" Position="0" InstanceNumber="1" minPixel="-32768.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="15" seriesUID="1.2.276.0.7230010.3.200.3.15" SeriesDescription="16 in 16,range -32768 to +32767,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.15.1" Position="0" InstanceNumber="1" minPixel="-32768.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="16" seriesUID="1.2.276.0.7230010.3.200.3.16" SeriesDescription="16 in 16,range -32768 to +32767,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.16.1" Position="0" InstanceNumber="1" minPixel="-32768.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="17" seriesUID="1.2.276.0.7230010.3.200.3.17" SeriesDescription="16 in 16,range -16384 to +16383,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.17.1" Position="0" InstanceNumber="1" minPixel="-32768.0" maxPixel="32768.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="18" seriesUID="1.2.276.0.7230010.3.200.3.18" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono2,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.18.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="19" seriesUID="1.2.276.0.7230010.3.200.3.19" SeriesDescription="12 in 16,range -2048 to +2047,signed,mono1,no luts" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.19.1" Position="0" InstanceNumber="1" minPixel="-2048.0" maxPixel="2048.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="20" seriesUID="1.2.276.0.7230010.3.200.3.20" SeriesDescription="inappropriate modality lut transform" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.20.1" Position="0" InstanceNumber="1" minPixel="1024.0" maxPixel="770.0">
</image>
</series>
<series xsi:type="seriesBean" Viewable="1" SeriesNumber="21" seriesUID="1.2.276.0.7230010.3.200.3.21" SeriesDescription="inappropriate modality lut transform" Modality="OT">
<image xsi:type="imageBean" Rows="512" Columns="512" objectUID="1.2.276.0.7230010.3.200.3.21.1" Position="0" InstanceNumber="1" minPixel="-1024.0" maxPixel="-1533.0">
</image>
</series>
<series xsi:type="seriesBean" seriesUID="PR:1.2.276.0.7230010.3.200.3" Modality="PR">
<gsps presentationDateTime="1999-11-17T08:30:08.000-05:00" contentLabel="MLUT_P01" objectUID="1.2.276.0.7230010.3.200.3.0.1">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:10.000-05:00" contentLabel="MLUT_P02" objectUID="1.2.276.0.7230010.3.200.3.0.2">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:11.000-05:00" contentLabel="MLUT_P03" objectUID="1.2.276.0.7230010.3.200.3.0.3">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:13.000-05:00" contentLabel="MLUT_P04" objectUID="1.2.276.0.7230010.3.200.3.0.4">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:14.000-05:00" contentLabel="MLUT_P05" objectUID="1.2.276.0.7230010.3.200.3.0.5">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:16.000-05:00" contentLabel="MLUT_P06" objectUID="1.2.276.0.7230010.3.200.3.0.6">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:17.000-05:00" contentLabel="MLUT_P07" objectUID="1.2.276.0.7230010.3.200.3.0.7">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:19.000-05:00" contentLabel="MLUT_P08" objectUID="1.2.276.0.7230010.3.200.3.0.8">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:20.000-05:00" contentLabel="MLUT_P09" objectUID="1.2.276.0.7230010.3.200.3.0.9">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:22.000-05:00" contentLabel="MLUT_P10" objectUID="1.2.276.0.7230010.3.200.3.0.10">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:24.000-05:00" contentLabel="MLUT_P11" objectUID="1.2.276.0.7230010.3.200.3.0.11">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:26.000-05:00" contentLabel="MLUT_P12" objectUID="1.2.276.0.7230010.3.200.3.0.12">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:28.000-05:00" contentLabel="MLUT_P13" objectUID="1.2.276.0.7230010.3.200.3.0.13">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:29.000-05:00" contentLabel="MLUT_P14" objectUID="1.2.276.0.7230010.3.200.3.0.14">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:31.000-05:00" contentLabel="MLUT_P15" objectUID="1.2.276.0.7230010.3.200.3.0.15">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:32.000-05:00" contentLabel="MLUT_P16" objectUID="1.2.276.0.7230010.3.200.3.0.16">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:34.000-05:00" contentLabel="MLUT_P17" objectUID="1.2.276.0.7230010.3.200.3.0.17">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:35.000-05:00" contentLabel="MLUT_P18" objectUID="1.2.276.0.7230010.3.200.3.0.18">
</gsps>
<gsps presentationDateTime="1999-11-17T08:30:38.000-05:00" contentLabel="MLUT_P19" objectUID="1.2.276.0.7230010.3.200.3.0.19">
</gsps>
<gsps presentationDateTime="2000-06-28T12:00:00.000-04:00" contentLabel="MLUT_P20" objectUID="1.2.276.0.7230010.3.200.3.0.20">
</gsps>
<gsps presentationDateTime="2000-06-28T12:00:00.000-04:00" contentLabel="MLUT_P21" objectUID="1.2.276.0.7230010.3.200.3.0.21">
</gsps>
</series>
</study>
</patient>
</results>
