<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<results xmlns="http://www.dcm4chee.org/xero/search/study/" xmlns:ns2="http://www.w3.org/2000/svg" xmlns:ns3="http://www.w3.org/1999/xlink">
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="patientBean" PatientName="Modality^LUT^PState^Test" PatientIdentifier="MLUT_Pnn" PatientID="MLUT_Pnn">
<study xsi:type="studyBean" StudyDateF="17-Nov-1999 8:30:08 AM" studyUID="1.2.276.0.7230010.3.200.3" StudyID="MLUT_Pnn" StudyDescription="Modality LUT PState Test" StudyDateTime="1999-11-17T08:30:08.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="22" NumberOfStudyRelatedInstances="42" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
<study xsi:type="studyBean" StudyDateF="17-Nov-1999 8:30:40 AM" studyUID="1.2.276.0.7230010.3.200.4" StudyID="VLUT_Pnn" StudyDescription="VOI LUT PState Test" StudyDateTime="1999-11-17T08:30:40.000-05:00" ReferringPhysicianName="Riesmeier^Joerg" NumberOfStudyRelatedSeries="13" NumberOfStudyRelatedInstances="24" ModalitiesInStudy="PR,OT" InstanceAvailability="ONLINE">
</study>
</patient>
</results>
